### ISSUE TITLE
Consider highlighting trailing space when encountering MD009

### ISSUE THREAD

**Issue by AndrewGaspar** [DavidAnson/vscode-markdownlint#1]
Currently when MD009 is encountered, the entire line is highlighted to indicate that there is a trailing space. This is distracting when you're constantly typing. Highlighting just the last space, or perhaps not showing the error indication if the cursor is currently active on the line would make it less obtrusive.

![line highlight](https://cloud.githubusercontent.com/assets/2292643/11860271/f149254c-a427-11e5-9e86-655e17391725.PNG)

**Comment by DavidAnson** [comment]
I like the idea of being more specific with underlining! MD009 is a great example of a rule that would benefit, and I can think of a few more pretty easily. I want think a bit more about exactly where this logic belongs, but should be able to make a first pass at this before too long. Thank you!

**Comment by AndrewGaspar** [comment]
Sweet, thanks for fixing this!

**Comment by DavidAnson** [comment]
:) Update your plugin to version 0.3.0 to try this in action!
