### ISSUE TITLE
[Bug] Config update needs a reload

### ISSUE THREAD

**Issue by Stanzilla** [DavidAnson/vscode-markdownlint#103]
When I change my .markdownlint.json and then close and reopen a file, VSCode still lints with the old rules, I have to reload the VSCode window for them to apply.

**Comment by DavidAnson** [comment]
Huh, I do this pretty regularly. When you save the JSON file, it should clear the cache and reload when you switch back to the MD file. I’ll experiment soon.

Actually, one reason this might not work for you is if the JSON file is not part of the open project/folder? The messages written to the output window (bottom pane, second tab if I remember right) may help understand what’s going on here.

**Comment by Stanzilla** [comment]
The JSON file is part of the folder, maybe because my project is inside of a WSL container?

**Comment by DavidAnson** [comment]
I think you figured it out. The extension asks VS Code to notify it whenever that file changes. That notification works fine in my experience, but I do not test with containers. If you try your same scenario outside a container and find that it works, then it should confirm what’s going on here.

**Comment by DavidAnson** [comment]
This sounds pretty similar: https://github.com/microsoft/vscode-remote-release/issues/870

**Comment by Stanzilla** [comment]
Yup, can confirm that it works in a normal Windows path. And I'm on WSLv1 but might be the same issue?

**Comment by DavidAnson** [comment]
Seems like. I think we’ll need to wait for WSL or VS Code to fix this.

**Comment by Stanzilla** [comment]
Sad :/ Wanna leave this open for tracking or should I close?

**Comment by DavidAnson** [comment]
I’d prefer to close it since there’s seemingly nothing to be done about it here.
