### ISSUE TITLE
.markdownlintignore file does not seem to be supported

### ISSUE THREAD

**Issue by difosfor** [DavidAnson/vscode-markdownlint#106]
It looks like this extension does not support the use of a .markdownlintignore file to specify which files should not be linted.

Currently, when I open a Markdown file which is ignored according to the .markdownlintignore file I will subsequently see warnings for that file in the Problems panel. In contrast; when I run markdownlint-cli like so: `markdownlint "**/*.md"` that file is ignored as expected.

PS: Thanks for all of your work on markdownlint!

**Comment by DavidAnson** [comment]
This extension was first to ignore and did so by supporting a configuration value: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintignore

With the addition of ignore file support to the CLI, I agree that should be added here.
