### ISSUE TITLE
Support .mlintrc file or similar

### ISSUE THREAD

**Issue by jrschumacher** [DavidAnson/vscode-markdownlint#108]
Instead of using the vscode workspace, for large teams, it would be nice if this supported `.mdlrc` or similar.

`.mdlrc` seems to be a common convention
https://github.com/markdownlint/markdownlint/issues?utf8=%E2%9C%93&q=is%3Aissue+.mdlrc+

**Comment by DavidAnson** [comment]
That file name is specific to the Ruby implementation of markdownlint, but you can use the file `.markdownlint{.json,.yaml,.yml,rc}` with this extension and the Node.js CLI as outlined here: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

**Comment by jrschumacher** [comment]
That's awesome! I was looking for something like that but must have skimmed over it.

**Comment by jrschumacher** [comment]
Created a #109 for a future release. I'm going to use one of the conventions you mentioned.
