### ISSUE TITLE
How to use katex

### ISSUE THREAD

**Issue by NeroBurner** [DavidAnson/vscode-markdownlint#110]
I'd like to use katex markdown like \`\`\`math (for block-mode) and $\` \`$ (for inline-math), because those are supported by gitlab's markdown rendering. And I'd like to preview my changes before pushing them to gitlab.

I've found the following two places mention `katex`, but I have no idea how to enable support in linting and also how to properly show math forumlas in the preview
- https://github.com/DavidAnson/vscode-markdownlint/blob/f42ae1f45f06c212f2ce269c9675d1d34a29b097/extension.js#L275
- https://github.com/DavidAnson/vscode-markdownlint/blob/1202626b308b1b9cd15b478785cda4b94960d997/package.json#L35

thanks in advance

**Comment by DavidAnson** [comment]
As you note, this extension is aware of math blocks as code blocks due to this commit: https://github.com/DavidAnson/vscode-markdownlint/commit/bd71955cf99bc0ace103b7b7fa121435446f5e32

Regarding your questions about rendering math blocks in the preview, I think you will find the topic is addressed in this issue: https://github.com/DavidAnson/vscode-markdownlint/issues/90

**Comment by NeroBurner** [comment]
I'm now using `markdownlint` together with [markdown-preview-enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)

I had to add the following setting to `settings.json` for inline math tags to work properly in the preview
```json
{
    "markdown-preview-enhanced.mathInlineDelimiters": [
        [
            "$`",
            "`$"
        ],
        [
            "$",
            "$"
        ],
        [
            "\\(",
            "\\)"
        ]
    ]
}
```

Thanks for your help and your awesome linter extension!

**Comment by DavidAnson** [comment]
Cool!

**Comment by NeroBurner** [comment]
for reference: PR to add the needed tags by default https://github.com/shd101wyy/vscode-markdown-preview-enhanced/pull/324

if/when the PR gets merged the manual configuration is not needed anymore
