### ISSUE TITLE
MD037 doesn't ignore emphasis markers within code span elements

### ISSUE THREAD

**Issue by Road-hog123** [DavidAnson/vscode-markdownlint#113]
A `code_span` with an odd number of emphasis markers followed later by an _emphasised word or phrase_ results in [MD037](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md037) being raised for the section between the first two emphasis markers, despite the first marker being within a pair of backticks.

The emphasis markers do not have to match:

- `code_span` followed by *emphasis*
- `code*span` followed by _emphasis_

It also happens when a `code_ span` is followed by another `code _span`, but having one with the required emphasis markers and space is much less common.

![image](https://user-images.githubusercontent.com/12716638/80210735-28d5ba80-862c-11ea-9b31-079f439eff77.png)

VSCode 1.44.2
markdownlint 0.35.0

**Comment by DavidAnson** [comment]
Sorry, this is a consequence of rewriting the rule to add some other behavior.

Tracked in the library here: https://github.com/DavidAnson/markdownlint/issues/278

**Comment by DavidAnson** [comment]
This should be fixed in the `0.35.1` release I've just published. Thanks for reporting it!
