### ISSUE TITLE
markdownlint raises unwanted warning about duplicate headers under different parallel headings

### ISSUE THREAD

**Issue by FremdSprach** [DavidAnson/vscode-markdownlint#117]
Issue Type: <b>Bug</b>

As title, this warning is kinda un-necessary.

### h3_1

It will be ok if there is a warning about the two duplicate **h3_1**'s under **h2_1**, but it's sort of weird warning about **h2_2** > **h3_1** duplicate.

Extension version: 0.35.2
VS Code version: Code - Insiders 1.46.0-insider (876f2e70f9a2e1988887f8ca82294418afac15a2, 2020-05-27T05:43:41.115Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DavidAnson** [comment]
Documentation for MD024/no-duplicate-heading includes an explanation of why it does this and can be found here: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md024

To enable duplicate headings at different levels, please set the `siblings_only` parameter to `true` as shown there.
