### ISSUE TITLE
Support EditorConfig for configuration

### ISSUE THREAD

**Issue by ejball** [DavidAnson/vscode-markdownlint#120]
It would be great if we could configure markdownlint in an [`.editorconfig`](https://editorconfig.org/) file. The syntax could be very similar to the JSON configuration, e.g. the [options.config example](https://github.com/DavidAnson/markdownlint#optionsconfig) could look something like this:

```
[*.md]
markdownlint.default = true
markdownlint.MD003.style = atx_closed
markdownlint.MD007.indent = 4
markdownlint.no_hard_tabs = false
markdownlint.whitespace = false
```

**Comment by DavidAnson** [comment]
The proposed configuration would be specific to `markdownlint` - and the VS Code extension as well as both CLI's already support `.markdownlint.json`/`.markdownlint.yaml` formats for this purpose. Adding another file and format across the tooling feels like it adds more complexity than it's worth. Thanks for the suggestion!
