### ISSUE TITLE
How to disable linting for current file?

### ISSUE THREAD

**Issue by NeoFantom** [DavidAnson/vscode-markdownlint#123]
I need to disable markdownlint for some specific file which is so small that I don't want to follow the rules at all. Or *disable temporarily* also works fine. How do I do that?

**Comment by DavidAnson** [comment]
You can disable one or more files via configuration as described here: ￼https://github.com/DavidAnson/vscode-markdownlint#markdownlintignore

Or you can run the `markdownlint.toggleLinting` command to temporarily disable linting as described here: ￼ https://github.com/DavidAnson/vscode-markdownlint#rules

**Comment by ayoubzulfiqar** [comment]
# Markdown Config

You can basically add any rule like which one you wanna enable or disable inside your Settings.JSON file
```json
"markdownlint.config": {
        "no-hard-tabs": false
    }
```
