### ISSUE TITLE
Question: Supporting markdownlint-cli2 config files

### ISSUE THREAD

**Issue by spbrogan** [DavidAnson/vscode-markdownlint#130]
Hi,

Just trying to understand how others might do this. 

1. I want to lint my markdown in both local editors (like vs code) and during CI of my project and would like the configuration to be controlled by the same files. 

2. Because i have a large project I want to allow different levels of config files (one at repository root) and then some inside folders within the code tree

3. The config i need to allow to be distributed is ignore files.

This plugin seems to support a .markdownlintignore at the root but not distributed throughout.  

The markdownlint-cl2 project looks like it could support distributed ignore configuration with multiple config files at different levels but this plugin does not use these config files.   Is that true?  

Do others have a way to solve this?  Am I missing something in the config or editor plugin?  

Thanks

**Comment by DavidAnson** [comment]
You're not missing anything - this is a new TODO with the release of `markdownlint-cli2` that allows more flexible configuration.

That said, why do you need to ignore so many files and could that be expressed in a file at the root?

**Comment by spbrogan** [comment]
There is no "one" root.  

1. In the Projects we work in a workspace has multiple repositories.  Each of these repositories are a project on their own.  This isn't really a problem except any repo could add/remove submodules and ideally this information is handled in that repo.  

2. Inside each repo it has different packages and those packages are owned by different groups, companies, etc and thus they have different dev cycles and timelines.  So it is nice if at the package level we can provide autonomy while still having centralized CI/tools/process.  A package can also add/remove submodules and again aligning control with ownership is the goal. 

Is it on your roadmap to switch to cli2 for the plugin?

**Comment by DavidAnson** [comment]
Your scenario makes sense, thanks! The VS Code plugin does not reuse the CLI; it has different needs. But I had thought to support the new `.markdownlint-cli2.jsonc` format.

**Comment by spbrogan** [comment]
So fast to reply.  I was just editing my comment to add a big thank you.  

Regardless of this enhancement I appreciate your efforts on these plugins and tools.  These have helped me put policies in place to enforce consistency across our documentation.

**Comment by DavidAnson** [comment]
Thanks! One quick thought: if you are you using VS Code support for multi-root workspaces, this could work today. https://code.visualstudio.com/docs/editor/multi-root-workspaces

Each workspace gets its own .vscode config which can include ignores. This scenario is not super well tested so far, but should work today.

Let me know if you try!

**Comment by DavidAnson** [comment]
As of https://github.com/DavidAnson/vscode-markdownlint/commit/e547e5674eb034c437a9cbf38d9c9802c23e30eb, the VS Code `markdownlint` extension uses `markdownlint-cli2` for linting and therefore supports the same features - including `.markdownlint-cli2.{jsonc,yaml,js}`.

**Comment by spbrogan** [comment]
sounds great.  I'll look for the next release.  Thanks again.

**Comment by DavidAnson** [comment]
Should be in a week or so.

**Comment by DavidAnson** [comment]
Now available in v0.40.2. Please see the release notes at the bottom of: https://github.com/DavidAnson/vscode-markdownlint/blob/main/CHANGELOG.md
