### ISSUE TITLE
MD032/blanks-around-lists triggers when using LaTex block

### ISSUE THREAD

**Issue by bathtown** [DavidAnson/vscode-markdownlint#133]
when I write something like this:

```md
- a bullet list

  $$
  e = mc^2
  $$
```

it says `MD032/blanks-around-lists: Lists should be surrounded by blank lines` on this line `e = mc^2` ( I use 2 indents on LaTex blocks ). but why?

**Comment by DavidAnson** [comment]
It looks like I may need to address this in the library after all. I should know more soon.

**Comment by DavidAnson** [comment]
This should be fixed in the next version of the library by https://github.com/DavidAnson/markdownlint/commit/32db81b7405ef3adad94934b2c1daeb59b8ce92e

**Comment by DavidAnson** [comment]
Should be fixed in `v0.38.0`.
