### ISSUE TITLE
How fix lint issues

### ISSUE THREAD

**Issue by yordis** [DavidAnson/vscode-markdownlint#135]
Would be amazing if the plugin could fix some of the issues like 

- MD013/line-length
- MD032/blanks-around-lists

Or any other issue that is fixable without breaking the code

**Comment by DavidAnson** [comment]
MD032 is fixable already. Details at the bottom of this section of the docs: https://github.com/DavidAnson/vscode-markdownlint#rules

MD013 is not fixable because the right thing to do is fairly complex. More info here: https://github.com/DavidAnson/markdownlint/issues/261
