### ISSUE TITLE
MD024 - Set siblings_only to true by default

### ISSUE THREAD

**Issue by jpmorin** [DavidAnson/vscode-markdownlint#144]
[MD024 - Multiple headings with the same](https://github.com/DavidAnson/markdownlint/blob/v0.21.1/doc/Rules.md#md024)

I want to set `siblings_only: true` for every project open in vscode, but I could not find how to set it globally.

Is there a way to configure rules globally? I do not want to create `.markdownlint` for every project for this single rule.

Thank you.

**Comment by DavidAnson** [comment]
If you make the change you want in VS Code user settings, it will automatically apply to loose files and every project that does not include its own configuration. More details here: https://github.com/DavidAnson/vscode-markdownlint#markdownlintconfig
