### ISSUE TITLE
Markdownlint ignores  "MD013": { "line_length": 500 }, in markdownlint.json

### ISSUE THREAD

**Issue by michaelbowler** [DavidAnson/vscode-markdownlint#147]
Hi David,

Liking MDLint but, when I set markdownlint.json as follows:

{
 ...
  "MD013": { "line_length": 500 },
 ...
}

But when I run markdownlint I get loads of : "...MD013/line-length Line length [Expected: 80; Actual: 169]"

Setting line_length to `False` has no effect either. 

I'm running on Win10 - any ideas on how to resolve this?

Thanks in adv.
MJB

**Comment by nschonni** [comment]
Are you missing the leading period on `.markdownlint.json`? Just a guess from the text of your question

**Comment by michaelbowler** [comment]
D'oh - knew it was something simple - thanks @nschonni
