### ISSUE TITLE
Request to support .markdownlintignore file in every directory instead of just the root of the project

### ISSUE THREAD

**Issue by 0xW1sKy** [DavidAnson/vscode-markdownlint#148]
Updating this post, as I just figured out the issue.

My Scenario:

## Does Not Work
VSCode Workspace
 ┣📦Project Folder (git repo)
 ┃ ┣ 📂Folder
 ┃ ┃ ┣ 📂SubFolder
 ┃ ┃ ┃ ┣ 📂SubFolder2
 ┃ ┃ ┃ ┃ ┣ 📂SubFolder3
 ┃ ┃ ┃ ┃ ┃ ┣ 📂SubFolder4
 ┃ ┃ ┃ ┃ ┃ ┃ ┗ 📜Readme.md
 ┃ ┗📜.markdownlintignore
 

## Works
VSCode Workspace
┣📦Project Folder (git repo)
┃ ┃ ┣ 📂Folder
┃ ┃ ┃ ┣ 📂SubFolder
┃ ┃ ┃ ┃ ┣ 📂SubFolder2
┃ ┃ ┃ ┃ ┃ ┣ 📂SubFolder3
┃ ┃ ┃ ┃ ┃ ┃ ┣ 📂SubFolder4
┃ ┃ ┃ ┃ ┃ ┃ ┃ ┗ 📜Readme.md
┗ 📜.markdownlintignore

Request making .markdownlintignore apply to the children of the folder it is placed in rather than to the vscode workspace all-or-nothing, this would be closer to the .gitignore functionality that I use today, mainly because I have ~12 or so separate git repos in my vscode workspace at any given time, this also makes it easier for me to package the ignore file with the repo.

**Comment by DavidAnson** [comment]
The handling of `.markdownlintignore` is implemented the same as the `markdownlint.ignore` user/workspace config: <https://github.com/DavidAnson/vscode-markdownlint#markdownlintignore>. The latter is necessarily associated with the workspace, so it is consistent for the former to be as well.

That said, a fix for the more general #130 (planned) would enable your scenario.
