### ISSUE TITLE
Opening a new markdown file, automatically opens an empty package.json file

### ISSUE THREAD

**Issue by itsgg** [DavidAnson/vscode-markdownlint#150]
Whenever I try to open a new markdown file, an empty package.json is auto-created 

![image](https://user-images.githubusercontent.com/1752073/105907192-b1b1d480-604a-11eb-9248-86bcb4a2cae6.png)

**Comment by DavidAnson** [comment]
That's not something this extension does. You can please confirm that by disabling or uninstalling it.

**Comment by itsgg** [comment]
Yes, @DavidAnson I tried disabling/uninstalling. When I do that the issue is not there. Wondering if it has to do something with this

![image](https://user-images.githubusercontent.com/1752073/105936274-64009080-6079-11eb-845d-4ec241de2a84.png)

**Comment by DavidAnson** [comment]
That code is not run by the extension and if it were, it would not cause VS Code to open the document.

What are the steps to produce the behavior you are seeing? Is there an empty package.json in that location already?

**Comment by itsgg** [comment]
It happens only when I open a new md file like

code README.md

and there is no package.json  present.

**Comment by DavidAnson** [comment]
I'll try this myself when I'm at a computer. But note that the VS Code API to open documents is `openTextDocument` and it does not appear anywhere in the source code of this extension: https://github.com/DavidAnson/vscode-markdownlint/search?q=openTextDocument&type=

**Comment by DavidAnson** [comment]
Can you try adding `-n` to your command? https://stackoverflow.com/questions/31270774/visual-studio-code-always-reopens-previous-file-or-folder

Maybe also `--disableExtensions`? https://github.com/microsoft/vscode/issues/114102

**Comment by itsgg** [comment]
@DavidAnson You are right the problem seems to be in the VS Code itself and not in your extension. Thanks for creating an awesome extension! Explanation video below, let me know if you have any questions. 

https://youtu.be/F4q_2L9R500

**Comment by DavidAnson** [comment]
I watched the video - that's really strange! Glad you figured it out, thanks for the help.
