### ISSUE TITLE
[Feature Request]: Fix All auto-fixable issues 

### ISSUE THREAD

**Issue by Kangie** [DavidAnson/vscode-markdownlint#151]
I'm in the process of implementing a CI-based document production system with MarkdownLint as a key part of this. 

While the vscode addon makes identifying linting issues a breeze, it would be really nice if I could fix auto-fixable issues from within the IDE; e.g. no-trailing-spaces, blanks-around-fences, blanks-around-lists,  blanks-around-headers, etc.

Otherwise, this has been a fantastic tool to get my Devs to produce easily (and consistently) parsed content. Thanks!

**Comment by DavidAnson** [comment]
You can read how to do this at the bottom of the section: https://github.com/DavidAnson/vscode-markdownlint#rules

**Comment by Kangie** [comment]
I'll certainly use that option from the command palette! 

Is it possible to add a context menu item to do this as an action from a linting error?

**Comment by DavidAnson** [comment]
I'll look into this.
