### ISSUE TITLE
Add JSON Schema support for '.markdownlintrc' config files

### ISSUE THREAD

**Issue by YashTotale** [DavidAnson/vscode-markdownlint#155]
Currently, `.markdownlint.json` config files have JSON schema support. It would be great if `.markdownlintrc` files also had JSON schema support.

**Comment by DavidAnson** [comment]
As of https://github.com/DavidAnson/vscode-markdownlint/commit/e547e5674eb034c437a9cbf38d9c9802c23e30eb the VS Code extension will use `markdownlint-cli2` for linting. As part of that, a couple of things will *no longer* be supported. `.markdownlintrc` is one of them - its JSON format is redundant with `.markdownlint.{json,jsonc}`, its INI format was never supported, and path resolution was never consistent with `markdownlint-cli` behavior.
