### ISSUE TITLE
[Question] How to make it consistent with CommonMark

### ISSUE THREAD

**Issue by chachan** [DavidAnson/vscode-markdownlint#156]
I was checking this file https://github.com/joelparkerhenderson/monorepo_vs_polyrepo/blob/master/README.md

and vscode shows me 138 problems. I didn't know about CommonMark until this https://github.com/joelparkerhenderson/monorepo_vs_polyrepo/pull/5. Now I wanted to enable a set of rules or a mode that helps me to be consistent with CommonMark but couldn't find the way. Is there a way fo achieve this using this extension?

**Comment by DavidAnson** [comment]
Sorry, I don't understand the question. CommonMark is a specification for Markdown. This extension uses a CommonMark-compliant parser and reports on a set of issues that are both violations of the specification as well as stylistic. Addressing all of the issues this extension reports will produce a document that is compliant with the CommonMark specification. But the Markdown format is flexible enough that this is probably not necessary to get satisfactory rendering from something like GitHub.

**Comment by chachan** [comment]
Understood, thanks for the clarification.
