### ISSUE TITLE
MD034 fix using Quick Fix

### ISSUE THREAD

**Issue by martincook3** [DavidAnson/vscode-markdownlint#159]
If the text cursor is at the end of the URL string when fixing an [MD034](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034) warning using Quick Fix, the last 2 characters of the URL are left selected so it's not possible to just continue typing as the 2 characters are overwritten. Please can the cursor be positioned immediately after the closing angle bracket in this scenario.  

No characters are left selected if the cursor is at the beginning of or anywhere within the URL. However, when the cursor is within the URL its index position within the string remains the same after the fix but this means that its textual position within the URL has moved left by 1 character.

**Comment by DavidAnson** [comment]
I'm not seeing a selection get created no matter how I invoke the quick fix - could you please be specific about what platform you're using and exactly what you do to perform the quick fix?

That said, I do see what you're saying about the cursor position remaining the same (line/column) and therefore moving left one relative to the content. Any existing selection maintains its start/end line/column, so also seems to shift. Right now, the extension does not try to maintain cursor position during an edit. In general, that could be a very difficult thing to do, though it's seemingly straightforward in this case, but not represented in the "fix" information the `markdownlint` library emits.

So I'm not sure how practical maintaining cursor position is, but I'll think about it more. However, I would like to understand how selection seems to be getting introduced in your case, so please let me know how to reproduce that!

**Comment by martincook3** [comment]
Thanks for your reply.
I'm using
![VSCode](https://user-images.githubusercontent.com/54174798/115702898-636a5400-a361-11eb-9626-ed07b31c1cdc.PNG)

with all extensions except markdownlint disabled, on Windows 10 (1809).

To perform the quick fix I use the keyboard shortcut Ctrl+.

https://user-images.githubusercontent.com/54174798/115703183-ba702900-a361-11eb-9e1d-ce842dba5e77.mp4

As you can see, the trailing / and > are left selected.

**Comment by DavidAnson** [comment]
Your cursor is at the end of the file and I was trying in the middle - that may be the trick. I'll experiment more soon. Thanks!

**Comment by martincook3** [comment]
It happens for me in the middle of the file as well.

**Comment by DavidAnson** [comment]
This reproduces for me when the URL is at the end of the file - and I can get it to happen with the URL in the middle of the file IF the URL is the last thing on its line. In any case, it happens for me ONLY when the cursor is after the last character of the URL when the fix is applied - no selection is created if it is in the middle of the URL. Thanks for the report.

**Comment by DavidAnson** [comment]
In this case, the extension is simply using the VS Code `TextEditorEdit` API to replace the text of the line (as identified by VS Code) with different text that has the fix. The selection behavior is implemented by VS Code. I think their current behavior is probably a bug, but I'm not sure there's a good way to avoid it from the extension and I'd be afraid that would break if/when they change this behavior. I'm inclined to close the issue.

https://github.com/DavidAnson/vscode-markdownlint/blob/36e6a69d62de445f7e446d7938c0274ed66501b8/extension.js#L387

**Comment by martincook3** [comment]
In that case, I agree, it's not for you to fix. (Can you contact anyone in the VS Code team about their probable bug?)
Thank you for investigating. I'll close the issue.

**Comment by DavidAnson** [comment]
Thanks for the suggestion at https://github.com/microsoft/vscode/issues/124154#issuecomment-889242379, @carlocardella!
