### ISSUE TITLE
Errors when a custom module is installed

### ISSUE THREAD

**Issue by af4jm** [DavidAnson/vscode-markdownlint#165]
I wrote a custom module that was working for a while, but now it just errors that it can't find the .js file, even though it's in the node_modules folder under both workspace folder and the directory in the workspace, and globally

``` json
        "markdownlint.customRules": [
            "node_modules/markdownlint-rule-olstart/rule.js"
        ]
```

**Comment by DavidAnson** [comment]
Please see the last bullet point here: https://github.com/DavidAnson/vscode-markdownlint/blob/main/CHANGELOG.md#about-release-0400

There's more of an explanation here: https://github.com/DavidAnson/vscode-markdownlint#markdownlintcustomrules

**Comment by af4jm** [comment]
OK, thanks... would be nice if there was a way to know updating an extension was introducing a breaking change, but that would open several cans of worms, both in VSCode itself & in extensions, especially in this case where the change only affects a small subset of users
