### ISSUE TITLE
Doest markdownlink try to use foreign diagnostics?

### ISSUE THREAD

**Issue by bartosz-antosik** [DavidAnson/vscode-markdownlint#17]
I have a strange situation here: When I use markdownlint with [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) (which I wrote) and it seems it is cannibalizing diagnostics produced by Spell Right:

![image](https://user-images.githubusercontent.com/20492548/31824045-33c74bf8-b5ae-11e7-9e9e-026a100a4ad5.png)

Could something be done about it?

**Comment by DavidAnson** [comment]
I’m not sure what you think vscode-markdownlint is doing wrong. It runs only for Markdown files and adds CodeDiagnostics for issues it finds. The VS Code API does not give it access to diagnostics from other extensions, so it can’t tamper with them.

The implementation is straightforward and I would encourage you to review my code to see if it’s doing anything you think is weird. Only the top message you show could be from markdownlint, but if it were, it would show a rule name, not “Vect”, so even that is strange. If you have a snippet that demonstrates bogus output from my code, please share it and I will have a look.

Aside: VS Code probably limits the total number of items in its list - perhaps that is what you are seeing?

**Comment by bartosz-antosik** [comment]
One way to solve it is: Somewhere around line 110:

![image](https://user-images.githubusercontent.com/20492548/31832464-6a7d52f0-b5c7-11e7-9ad9-1bd274236728.png)

You should set diagnostic.source to something (e.g. I set it to `spelling` you could to `markdownlint` etc.)

Then around line 122: 

![image](https://user-images.githubusercontent.com/20492548/31832664-1f05eaac-b5c8-11e7-9cd5-03606f179568.png)

You should check only diagnostics which come from your source.

What generates this strange `"Vect` is this: `diagnostic.message.substr(0, 5)`.

I am sorry I will not be able to make a PR.

**Comment by DavidAnson** [comment]
Thank you, I will look into this tonight and have a new release out soon. It seems strange  that VS Code doesn’t isolate diagnostics, but there is probably a good reason. Appreciate the help - reactivating this issue until I make a fix.

**Comment by DavidAnson** [comment]
Thanks again - the problem should be fixed in the next release of this extension! (Later this weekend.)

**Comment by bartosz-antosik** [comment]
Thank you. It is indeed fixed. 

![image](https://user-images.githubusercontent.com/20492548/31850840-611068cc-b65a-11e7-9169-eb90203386db.png)

I would personally shorten the source to markdownlint, but it's me maybe ;-):

![image](https://user-images.githubusercontent.com/20492548/31850838-45bf4e3a-b65a-11e7-8c79-ba16706af149.png)

**Comment by DavidAnson** [comment]
Noted. :) Thank you again!
