### ISSUE TITLE
Problem with images: The path d:\\2020-06-02-14-07-32.png doesn't exist on the disk

### ISSUE THREAD

**Issue by Creat1veM1nd** [DavidAnson/vscode-markdownlint#172]
Hello,

I do have some images in my markdown file, they are set as this: 

`![Alternate Text](2020-06-02-14-36-45.png)`

In preview mode, all images are shown correctly, since they are in the same folder as the markdown file itself. 

Though I am getting the error:
The path d:\\2020-06-02-14-07-32.png doesn't exist on the disk

I tried several variants of relative paths but none helped. The only way which made the message of an error (which is obviously no error) disappear, was to put in the whole absolute path. Which is not a good idea because of different absolute paths on different computer. 

I would like to igore that error but I did not find any option or error code to put it into the config file. 

So, any help appreciated!

Thanks in advance!

**Comment by DavidAnson** [comment]
Could you please show the error you are seeing? This does not sound like something markdownlint checks or warns about.

**Comment by Creat1veM1nd** [comment]
Thanks for pointing that out! I disabled markdownlint and the error message is still there. So it has to be any other addon or mechanism. 

Sorry for bothering! Will continue my investigation then.
