### ISSUE TITLE
Lint messages appear in all cells when editing a Markdown cell in Jupyter notebook

### ISSUE THREAD

**Issue by circumspect** [DavidAnson/vscode-markdownlint#174]
When editing a markdown cell in a Jupyter notebook which contains lint messages, the messages will appear in all of the other cells on the same line numbers, including code cells.

![image](https://user-images.githubusercontent.com/40770208/124671117-8d351080-dea4-11eb-90e5-8bc3cb7a543b.png)

(sidenote: it would be nice to be able to disable the first-line-heading/MD041 lint for all cells after the first one, but this is relatively minor)

**Comment by DavidAnson** [comment]
The extension isn't responsible for (and does not) render the text of linting violations.That is entirely the responsibility of VS Code or perhaps some other extension you are using. By default, violations show up in the "Problems" pane, not inline - my guess is that the implementation of Jupyter notebook cells is adding this behavior/problem.

Regarding treating multiple Markdown cells as a single document vs. separate documents (as seems to be the case now), I would also look to the Jupyter implementation. This extension operates at the VS Code "document" level.

**Comment by circumspect** [comment]
Ah yeah, the inline text would be Error Lens. I looked in the Problems pane and it seems like this is a result of line numbers being reset with each cell (the lint violations are listed as being on lines 1 and 5), so the only way to fix this is probably through VS Code directly. Thanks for taking a look!

**Comment by DavidAnson** [comment]
I've found that this scenario can be detected and Markdown blocks in a Jupyter notebook ignored entirely. Because these are not proper Markdown documents, that seems appropriate.
