### ISSUE TITLE
[FEATURE] Add support for emojis

### ISSUE THREAD

**Issue by MenaiAla** [DavidAnson/vscode-markdownlint#176]
#### Description

Sometimes, when I add emojis to my markdown, the extension displays the code of the emoji instead of its visual appearance.

**Comment by DavidAnson** [comment]
This extension does not have anything to do with the rendering of Markdown in VS Code. You may want something like these (untested by me):
- https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji
- https://marketplace.visualstudio.com/items?itemName=bierner.emojisense

**Comment by MenaiAla** [comment]
Exactly. Thank you for sharing this.
