### ISSUE TITLE
Rules override for unsaved files

### ISSUE THREAD

**Issue by OldStarchy** [DavidAnson/vscode-markdownlint#177]
Feature request, kinda similar to #93, but not really.

I often open up temporary markdown editors to take notes on what I'm currently doing and make todo lists. In those cases, I want to disable rules like `first-line-heading` and `single-trailing-newline`, since I don't often have a heading for these "files" and the trailing newline normally gets added on save, which doesn't happen for an unsaved editor.

I could disable markdownlint with the command mentioned in #93 but I only want it to apply to the unsaved editor, and there are only a few rules I'd like to disable.

**Comment by Pablion** [comment]
@OldStarchy, maybe you can use my current work-around: I set `markdownlint.run` to `onSave`

**Comment by DavidAnson** [comment]
I like that workaround for something that has only seemed to come up once in two years.
