### ISSUE TITLE
How do I turn off the suggestion that I use smart quotes?

### ISSUE THREAD

**Issue by BruceEckel** [DavidAnson/vscode-markdownlint#178]
![image](https://user-images.githubusercontent.com/1001900/125860829-f87feae0-1ac1-4252-9253-d066454f3a87.png)

I realize it's referring to LanguageTool, but I get the impression that LanguageTool is incorporated into markdownlint?

I've been going around on this one for awhile I can't see what or how to configure this. Any help is appreciated.

**Comment by DavidAnson** [comment]
LanguageTool is not related to markdownlint or bundled with it. Their project page seems to be here: https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languagetool

**Comment by BruceEckel** [comment]
OK, that helps clear some things up. But it's still a mystery how I ended up with it. My recollection was only installing markdownlint. Maybe something else uses it and then it automatically also started working on markdown files as well? I think I will try completely wiping VSCode off my machine and then installing markdownlint first, then see if the LanguageTool stuff appears at some later point (presumably after installing one of the other plugins).

FYI I couldn't find any way to turn off the LanguageTool smart quote recommendations.
