### ISSUE TITLE
Location of underline for MD042 when line has multiple links

### ISSUE THREAD

**Issue by alexcnichols** [DavidAnson/vscode-markdownlint#18]
The green underline for MD042 can be in the wrong location if the line contains multiple links.

In the below example, the underline should be under the word Package, not Plans.

![image](https://user-images.githubusercontent.com/19493383/31912254-206f20c0-b7f8-11e7-80c3-26d3c6b38ee1.png)

**Comment by DavidAnson** [comment]
Yes, thanks. Some of the highlights are based on RegExp for convenience and can be wrong like this.

**Comment by DavidAnson** [comment]
Sorry for the trouble, this should be better in the next release.

https://github.com/DavidAnson/markdownlint/commit/0fd322a3801c8f2874acead5cbba230a5b671e6b

**Comment by DavidAnson** [comment]
Please try new version `0.12.0`.

**Comment by alexcnichols** [comment]
Thank you!

![image](https://user-images.githubusercontent.com/19493383/33506143-5958dfec-d6a3-11e7-8e8f-a8a8156f8a4f.png)
