### ISSUE TITLE
Error: Cannot find module 'markdownlint-rule-titlecase'

### ISSUE THREAD

**Issue by dprothero** [DavidAnson/vscode-markdownlint#183]
I'm trying to use [markdownlint-rule-titlecase](https://www.npmjs.com/package/markdownlint-rule-titlecase) with the vscode extension. I have installed the module in my workspace directory like so:

```
npm install markdownlint-rule-titlecase --save-dev
```

And I've got this as my `.markdownlint-cli2.js`:

```
const titleCaseRule = require("markdownlint-rule-titlecase");

module.exports = {
  customRules: [titleCaseRule],
};
```

If I manually run `markdownlint-cli2`, it runs fine from the workspace directory and that custom rule is correctly used.

However, when vscode tries to lint, I get the error `Cannot find module 'markdownlint-rule-titlecase'`.

**Comment by DavidAnson** [comment]
Is that directory open in VS Code? Can you share a link to the repo (or a simplified repro) for me to try?

**Comment by DavidAnson** [comment]
I think I have verified this in the past (see dir2 at https://github.com/DavidAnson/markdownlint-cli2/tree/main/test/customRules), but I may be wrong. Under VS Code, they don't run the normal Node require and this has caused issues in the past.

**Comment by dprothero** [comment]
Ugh, it works if I create a fresh project. Unfortunately, I cannot share the project where it's not working.

**Comment by dprothero** [comment]
OK, a complete restart of vscode fixed the issue.
