### ISSUE TITLE
Editor loses focus on edit when a local copy of markdownlint is not installed

### ISSUE THREAD

**Issue by kachkaev** [DavidAnson/vscode-markdownlint#184]
👋

I cloned a repo with a local `markdownlint-cli` setup, forgot to run `yarn install` and started editing a markdown. Surprisingly, the editor ended up losing focus each time markdownlint was trying to check the file. This made typing pretty much impossible – here is how it looked:

![Kapture 2021-08-14 at 12 46 33](https://user-images.githubusercontent.com/608862/129445404-a932e6f8-5964-42b3-9a47-3bc7f11d4114.gif)

I typed two words. The first one got printed, but the other one got lost because I ended up typing into the output channel.

Looks like the problem is in how [`outputChannel.show()` is called](https://github.com/DavidAnson/vscode-markdownlint/blob/007db6eae1ad4d99597cf5514eb514f438eebf24/extension.js#L102). According to the [method signature](https://github.com/microsoft/vscode/blob/15c86782298a32e175b476673e1511d3ae43ed49/src/vs/vscode.d.ts#L5553-L5558), the problem should be fixeable by passing `true` as the first argument (which is `preserveFocus`). I did this in my local copy of the extension and it worked! The output channel still pops up (which is good), but the cursor remains in the editor.

**Comment by DavidAnson** [comment]
Released a version with the fix.
