### ISSUE TITLE
[Feature Request] Support tilde expansion in config

### ISSUE THREAD

**Issue by laggardkernel** [DavidAnson/vscode-markdownlint#186]
```jsonc
  "markdownlint.config": {
    // tilde is not supported
    "extends": "~/.config/markdownlint/config"
  },
```

Currently `~` is not supported in vscode-markdownlint configuration, but supported in default settings like `python.defaultInterpreterPath`, etc. Hope this feature could be supported.

Environments

- OS: macOS 10.14.6
- VSCode: 1.57.1
- vscode-markdownlint: 0.43.2

**Comment by DavidAnson** [comment]
This should work in the next update, via https://github.com/DavidAnson/markdownlint/commit/ffc4d569182a116c0233b2efc97353364c470702.
