### ISSUE TITLE
MD038 bug

### ISSUE THREAD

**Issue by rightaway** [DavidAnson/vscode-markdownlint#19]
This line reports an MD038 error between the first and second code areas.

```
- some text `.........`, `#####`
```

**Comment by DavidAnson** [comment]
Thanks! I think this will be fixed with the next dependency update: https://github.com/DavidAnson/markdownlint/commit/5fee0a921d09a3388141db8b12669161e56796cf

**Comment by DavidAnson** [comment]
Could you please double-check your sample - I do NOT get a MD038 error on that line in the latest public version. (Maybe there was a space and GitHub ate it?) Please try here: https://dlaa.me/markdownlint/

**Comment by rightaway** [comment]
I see the issue now. The markdown did have a space in it

```
`one`, `two`, `three `
```

but the problem underlining is happening between one and two, leading me to think that's where the problem was. The location of the underlining should be fixed I suppose.

**Comment by DavidAnson** [comment]
Yes, good, that’s the unreleased change. :)

**Comment by DavidAnson** [comment]
Your example is correctly underlined with version `0.11.1` - and is automatically fixable.
