### ISSUE TITLE
Disable rules by file extension

### ISSUE THREAD

**Issue by thielj** [DavidAnson/vscode-markdownlint#193]
Hi, is there a way to disable some rules for certain file extensions?

Use case: Jupyter / .NET interactive notebooks. The markdown "cells" are fragments unnecessarily triggering rules like MD041 or MD047.

**Comment by DavidAnson** [comment]
This is fixed in the next release, see #174. I had to pull that release due to a couple of issues with virtual file systems, but expect to re-release it this evening.

**Comment by relativityhd** [comment]
Maybe it could help to add support for `per-language configuration`, so we can disable specific rules just for jupyter notebooks?
<img width="478" alt="Screenshot 2021-09-24 at 17 22 56" src="https://user-images.githubusercontent.com/37540371/134700209-ca395e39-ebc7-4c07-a022-4a6eb5286f6e.png">

**Comment by DavidAnson** [comment]
The language will always be "Markdown"; it's the surrounding context that changes. Have a look at the commit associated with the issue I reference above to see how that's being detected and used to ignore this scenario.

**Comment by DavidAnson** [comment]
Released `0.44.2` a day later than I wanted, but got a needed fix in.

**Comment by thielj** [comment]
Many thanks!
