### ISSUE TITLE
ERROR: Exception while linting with markdownlint-cli2 on network share (\\server) in Windows

### ISSUE THREAD

**Issue by commputethis** [DavidAnson/vscode-markdownlint#196]
```
[6:44:00 PM] ERROR: Exception while linting with markdownlint-cli2:
Unknown (FileSystemError) (FileSystemError): Error: UNKNOWN: unknown error, stat '\\privatedrives\privatedrives\user\DaftPyPosh\vSphereSCG\README.md'
	at _handleError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:160527)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by commputethis** [comment]
switching to a drive letter did work as a workaround.  thanks

**Comment by DavidAnson** [comment]
Thanks! I mentioned in the related thread that it may be possible to work around this by using `net use` to map that share to a drive letter and opening from there.

**Comment by commputethis** [comment]
some additional information.  It probably isn't helpful, but I don't want to assume.  The file location was being accessed through a "Network Location".

![image](https://user-images.githubusercontent.com/17625274/134826924-8a8de2c5-7ca7-4442-9247-af665209cb87.png)

**Comment by commputethis** [comment]
@DavidAnson Thanks for your help!
