### ISSUE TITLE
The light bulb symbol that means "fix all supported markdownlint violations in this document" keeps appearing on the screen.

### ISSUE THREAD

**Issue by tnakaicode** [DavidAnson/vscode-markdownlint#197]
No matter where I place my cursor in the Markdown file, I keep getting a light bulb symbol that means "fix all supported markdownlint violations in this documents".
When I look at "Output" -> "markdownlint" or anywhere else in the file, I can't find the error. I'm guessing it's because I'm using something like "space two new lines", but since it doesn't tell me what part of the file it is, I can't fix it.

**Comment by DavidAnson** [comment]
Can you please link to the problem file or paste a simple example here!

**Comment by tnakaicode** [comment]
For example, the following picture shows the situation. When I select the light bulb symbol, I get the message "fix all supported markdownlint violations in this documents".

This is the case with almost all of my Markdown files, and it appears wherever I place the cursor in the same file.
I don't think there is a grammatical problem (I don't have a single warning), but it is very annoying to read because it keeps popping up.

![B0C34C1BB7AABA3A](https://user-images.githubusercontent.com/29787447/135183770-725fd011-8830-4ffe-9bb9-cd485b38faed.png)
https://github.com/tnakaicode/Note/blob/master/note_3d.md

**Comment by DavidAnson** [comment]
Understood, thanks, I have an idea why this might happen.
