### ISSUE TITLE
it will bring some warning

### ISSUE THREAD

**Issue by caoyi0905** [DavidAnson/vscode-markdownlint#2]
it will bring three warning in  vscode's setting.json:

`"git.path": null,`

`"typescript.tsdk": null,`

`"php.validate.executablePath": null,`

And it would not be regarded as warning

**Comment by DavidAnson** [comment]
The message you're seeing for those properties, `Incorrect path. Expected string.`, is not output by vscode-markdownlint. That message is part of VS Code's validation for settings. vscode-markdownlint messages will all be prefixed by "MD###" corresponding to the set of rules in the project README:
https://github.com/DavidAnson/vscode-markdownlint#rules
