### ISSUE TITLE
Support expanding focusMode range to allow N lines around the current line

### ISSUE THREAD

**Issue by OldStarchy** [DavidAnson/vscode-markdownlint#200]
In this situation, my cursor is on line 3 and I'm about to type something, but 
![image](https://user-images.githubusercontent.com/15243523/136310179-fafe4d4a-9ed5-4507-846d-90955eb6d16b.png)

When I enable "Focus Mode" to "hide violations on the current line" I still get this warning
![image](https://user-images.githubusercontent.com/15243523/136310431-4e7b630f-9b3a-4e22-bdbf-851b97d7bb65.png)

Is there a way to have the cursor act as a kind of psudo-character, for rules that require a character to be there, treat it as though there is (as it's likely I'm about to type). This would remove both of those warnings.

**Comment by DavidAnson** [comment]
I already have a note to consider allowing focusMode to extend N lines around the cursor. It seems like a setting of 1 would be what you mean here (in other words, one extra line above and below the cursor).￼

**Comment by OldStarchy** [comment]
In this specific case, a setting of `1` would remove these warnings, and that would probably work in most cases, but that's no guarantee.

What I'm suggesting is that the linter would treat the cursor as though it was a character in the document. I'd almost go so far as to actually place a character in that location before passing the document to the linter if I was sure that adding a character wouldn't cause more errors (like adding a character on the line preceding a list).

I used a `|` character to show what I mean in these screenshots.

"Virtual" character added in place of cursor prevents the warnings above
![image](https://user-images.githubusercontent.com/15243523/136315354-ea11dbfa-37f3-4efd-98cb-a35e0e315d46.png)

"Virtual" character added in place of cursor causes a warning
![image](https://user-images.githubusercontent.com/15243523/136315448-f92d1a0d-fc59-4bdd-bc2c-8699896cbb37.png)

**Comment by DavidAnson** [comment]
There are various scenarios where injecting a character would hide errors and lead to confusion. For example, "# | Heading" or "Line      |" or "-|--". I think it will be hard to get that right. Whereas buffering the current line in focusMode is a natural extension of something that's already available.

**Comment by DavidAnson** [comment]
Cool, I'll use this issue for that task.
