### ISSUE TITLE
settings.json keeps getting added/updated for every directory I open

### ISSUE THREAD

**Issue by heaths** [DavidAnson/vscode-markdownlint#204]
Despite having the following JSON in my user settings, it keeps getting added to `.vscode/settings.json` whether it was already there or not, causing extraneous, unwanted changes in my git repos:

```json
{
    "markdownlint.config": {
        "MD028": false,
        "MD025": {
            "front_matter_title": ""
        }
    }
}
```

Extension version: v0.44.4

<details>
<summary>VSCode information</summary>
```
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```
</details>

**Comment by nschonni** [comment]
@bharney0 is there any support channel now that the repo is archived?

**Comment by heaths** [comment]
FWIW, I uninstalled the extension pack, and installed back several extensions individually except the linter. Unfortunate, but this behavior was a major annoyance.

**Comment by DavidAnson** [comment]
To be clear, this extension can be added back without causing that issue - it's the docsmsft extension that is modifying those files.

**Comment by bharney0** [comment]
@jamarw would you be able to look into this? I believe the change you made to Docs Authoring Pack https://dev.azure.com/ceapex/Engineering/_git/DocsAuthoringPack/pullrequest/318687 is adding .vscode settings everytime you open a .md file.

**Comment by bharney0** [comment]
> @bharney0 is there any support channel now that the repo is archived?

I had been discussing this with my manager and I dont think they have any support story for issues using Docs Authoring Pack, which was one of the biggest reasons I suggested not to close sourcing the repo.

**Comment by heaths** [comment]
> To be clear, this extension can be added back without causing that issue - it's the docsmsft extension that is modifying those files.

Sorry, yes, that's what I meant. 🙂

**Comment by jamarw** [comment]
> @jamarw would you be able to look into this? I believe the change you made to Docs Authoring Pack https://dev.azure.com/ceapex/Engineering/_git/DocsAuthoringPack/pullrequest/318687 is adding .vscode settings everytime you open a .md file.

@bharney0 @heaths @DavidAnson @nschonni , I'll take a look now. You can also rollback the extension to the previous version while we implement a fix. Thanks and sorry for the inconvenience. 

![rollback-extension](https://user-images.githubusercontent.com/11825888/140830029-7a80ba75-cd32-46d3-92e5-f241caeabfd3.gif)

**Comment by heaths** [comment]
@jamarw so the extension(s) are still in active development - just not maintained in GitHub anymore (if ever - sounds like it was a mirror)? Good to know if my assumption is correct. Apart from this behavior, I otherwise love the extension pack.

**Comment by jamarw** [comment]
@heaths , yes the extensions are still in active development internally instead of publicly now. We used to rely on GitHub for user feedback so we're attempting to develop a new strategy to allow to report bugs, provide suggestions, etc. 

It's great to hear that the extension pack is helpful and we'll get the settings file issue addressed ASAP.

Thanks!

**Comment by nschonni** [comment]
@jamarw FYI, this is still happening
