### ISSUE TITLE
VSCode runs out of memory on "Fix all linting errors" job

### ISSUE THREAD

**Issue by svew** [DavidAnson/vscode-markdownlint#205]
I have markdownlint configured to automatically fix errors on file save. After somewhere between 15-30 minutes of use, and saving multiple times, a spike in memory usage seems to occur during the "Fix all linting errors" job after hitting save, which causes VSCode to slow down and crash with the following error:

```
The window has crashed (reason: 'oom', code: '-536870904')
```

This has happened 3 or 4 times now. Running version `0.45.0`, unsure what other info I can provide

**Comment by DavidAnson** [comment]
That's not a lot to go on... Can you disable fix-on-save for a while to confirm that's part of the problem?

**Comment by DavidAnson** [comment]
If so, any of the info gathering suggestions here could help: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by svew** [comment]
Thanks, I'll try to go through the steps, and reopen when I can give more helpful info
