### ISSUE TITLE
Stuck on `INFO: Linting for "file.md" will be run "onType"`

### ISSUE THREAD

**Issue by redactedscribe** [DavidAnson/vscode-markdownlint#207]
I don't know why but markdownlint has stopped functioning.

To try and solve the issue, I first downloaded the zipped version of VS Code and created the "data" directory to make it run in portable mode. Ran the program and installed markdownlint and tested a Markdown file. I see linting squiggles, it works, great. So that means there's an issue on my end.

After replacing the contents of the portable VS Code's "data" directory with a copy of my own user data and extensions, and then running the program again, I removed all my extensions one-by-one, except markdownlint, and reduced my VS Code json settings file down to 2 lines (unrelated to markdownlint: telemetry and how to restore windows). No matter what I edit in my "file.md", the extension still won't start linting as far as I can tell. The only line of output remains "...will be run onType". I also re-installed the final extension markdownlint and temporarily removed all presences of ".markdownlint.json[c]" from my systems but it makes no difference. After multiple program restarts, I'm out of ideas. By this point, I'd imagine this portable install is pretty bare-bones, and I don't know what could be the problem.

Do you have any pointers as to what could cause the extension to not function? I haven't noticed an issue with other extensions acting up.

Thanks!

markdownlint v0.45.0
VS Code 1.62.1

**Comment by redactedscribe** [comment]
Thanks so much!

**Comment by DavidAnson** [comment]
Sorry it took so long!
