### ISSUE TITLE
Spammy error opens output view

### ISSUE THREAD

**Issue by losnappas** [DavidAnson/vscode-markdownlint#208]
Sometimes I'm getting this error when I go backward in git history ("Open Change with Previous Revision") on a markdown file.

```
Error: Unable to parse '/home/.../.markdownlint.jsonc'; Unexpected end of JSON input
```

Then it doesn't let met close the output view at all, because every time I close it, the error opens it again. Any chance to remove the "auto-open" of this error, or just ignore this error altogether? I don't even have a `.markdownlint.jsonc` anywhere.

**Comment by DavidAnson** [comment]
You're probably using an extension for git history and it it storing paths in an unexpected way. If you can please identify it, I can fix the issue or exclude paths from that extension to stop the errors. Thanks!

**Comment by losnappas** [comment]
Cool, I'll try figuring it out once I have the time. For the record, the extension for going back/forward between revisions is gitlens. But I have many other extensions, so I'll have to do some testing.

**Comment by DavidAnson** [comment]
Start with gitlens. :) Thanks for the help!

**Comment by losnappas** [comment]
Well, I can at least give a reproduce consistently.

1. Create new markdown file
2. Save it and commit it
3. With gitlens, do "Open changes with previous revision"
4. error pops up

If I do `copy relative file path` when looking at the revision diff, it gives me a wonky path like this:

```text
home/user/projects/project-repo/asdf.md (a8f0630)
```

Seems to miss the initial `/` and obv the end has the hash in brackets.

**Comment by DavidAnson** [comment]
Thank you! Hopefully they've tagged this as being a non-standard file reference and I will be able to ignore it based on that tag. I hope to get to this in the next couple of weeks.
