### ISSUE TITLE
this is not show image ?

### ISSUE THREAD

**Issue by zhuamaodeyu** [DavidAnson/vscode-markdownlint#21]
i write and i preview ,but preview do not show image ?i use http url for image. so i don`t good show , can you add this ? please.

**Comment by DavidAnson** [comment]
Please provide example Markdown and describe what you expect.

Also, please read the section “Markdown Preview” here because it may explain how to do what you want: https://code.visualstudio.com/docs/languages/markdown

**Comment by DavidAnson** [comment]
I think the section “Markdown preview security” explains what you are seeing and how to change it.

(This is VS Code behavior, unrelated to the `markdownlint` extension.)

**Comment by DavidAnson** [comment]
Closing as this seems to have been addressed.
