### ISSUE TITLE
Feature request: Support VS Code's source code formatter API

### ISSUE THREAD

**Issue by PabloLION** [DavidAnson/vscode-markdownlint#211]
Hi, I liked the idea of keeping markdown rules in a file so a team can work in the same style, but I encountered one question.

I was using `esbenp.prettier-vscode` as my default formatter for markdown but they gives only 2 space for indent despite that I set it to four. Then I tried to set `DavidAnson.vscode-markdownlint` as the formatter but then I have an error of `Change Default Formatter` saying `Extension 'markdownlint' is configured as formatter but it cannot format 'Markdown'-files`. 

My problem is I am using "MD007/ul-indent - Unordered list indentation" with `"ul-indent": { "indent": 4 }` and the formatter will adjust to 2 always... I had to use command palette `save without formatting` every time.

Since there's already a `markdownlint.fixAll` command, maybe it's easy to convert to a formatter? (if it's not)

![image](https://user-images.githubusercontent.com/36828324/143658178-d9a1fcd9-79e4-4b31-8e14-dc7f98ea2e66.png)

![Change Default Formatter](https://user-images.githubusercontent.com/36828324/143657982-ae472032-b511-431e-a01f-559b8986cf80.png)

**Comment by DavidAnson** [comment]
As you discovered, this extension does not support being a formatter. You may also be right that it's not much work to support that. (Docs: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) I'll use this issue to track the feature request.

**Comment by Pablion** [comment]
> As you discovered, this extension does not support being a formatter. You may also be right that it's not much work to support that. (Docs: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) I'll use this issue to track the feature request.

Nice! Since you have all the logical functions written, I assume it would not be that hard to add a contribution point. And this function can really be really helpful.
(tl;dr) I marked it as question because when I searched Issues in this repo. I saw someone used it to format files so I was confused that maybe I don't know how to use it.

**Comment by PabloLION** [comment]
Tested. Singing like a charm. Thanks.
