### ISSUE TITLE
[Feature Request] Run from command-line for use in CI

### ISSUE THREAD

**Issue by marcusl** [DavidAnson/vscode-markdownlint#212]
Awesome extension, but it'd be nice to be able to run the linter from the command-line, to get a CI report on the markdown files.

Because sometimes people don't have the linter installed, or are editing markdown files directly from github web interface.

**Comment by DavidAnson** [comment]
Here is a CLI that exactly implements the code of this extension: https://github.com/DavidAnson/markdownlint-cli2

If that's not what you want, please explain more.

**Comment by DavidAnson** [comment]
Oh, and here's that same thing in a GutHub Action: https://github.com/DavidAnson/markdownlint-cli2-action

**Comment by marcusl** [comment]
That is exactly what I was looking for! 😍 Thanks!
