### ISSUE TITLE
CSS style sheets location

### ISSUE THREAD

**Issue by martincook3** [DavidAnson/vscode-markdownlint#213]
VSCode 1.61.0
markdownlint 0.45.0
Windows 10

---

I can specify a style sheet in the root folder, or a child folder:

``` json
"markdown.styles": [
    "styles.css",
    "styles\\styles.css"
]
```

but if I move it to the parent folder
``` json
"markdown.styles": [
    "..\\styles.css"
]
```
then I get the error:
> Could not load 'markdown.styles': ..\styles.css

Why is this, please?

**Comment by DavidAnson** [comment]
I don't know. That is a feature of VS Code, not this extension. Please open an issue in their repository: https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css

**Comment by martincook3** [comment]
I'm sorry. I don't understand why I thought this was an issue with your extension. Thank you for pointing me in the right direction.

**Comment by DavidAnson** [comment]
Good luck! :)
