### ISSUE TITLE
focusMode configuration is not available 

### ISSUE THREAD

**Issue by jowitte** [DavidAnson/vscode-markdownlint#214]
I tried setting focusMode like this

`"markdownlint.focusMode": 2,`

but it doesn't seem to change anything. The setting isn't recognised as an available setting.

**Comment by DavidAnson** [comment]
Where are you setting that and what version of the extension are you using?

**Comment by jowitte** [comment]
I'm setting this in my workspace configuration file:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/8180200/145725735-cae4602f-9a64-4980-b591-f4ac108c6517.png">

The setting is marked as "not available". I'm using version 0.45.0 .

**Comment by DavidAnson** [comment]
Aha! This is an application-level setting and will only work from user settings. I will update the documentation.
