### ISSUE TITLE
Invalid MD037 raised on valid input

### ISSUE THREAD

**Issue by cdaringe** [DavidAnson/vscode-markdownlint#217]
# Problem

MD037 incorrectly raised on valid input

# Reproduction

<pre>
- "my_project/" as the _path_ to ...
     ^^^^^^^^^^^^^^^^^^
         MD037/no-space-in-emphasis: Spaces inside emphasis markers 
</pre>

# Discussion

I'm not clear on how the markdown grammar decides if a `_` char is emphasis associated or not, but certainly in this case it has identified the `_` in `my_project` incorrectly as emphasis

# Related

#444
#408

**Comment by DavidAnson** [comment]
This should be fixed in the next release of the library as indicated by the issues linked here: https://github.com/DavidAnson/markdownlint/commit/7cf9c2d6bee40e87aa5ad615f8b1fd75f33e4b36

The next release of this extension should have that update and resolve the issue.

**Comment by cdaringe** [comment]
thanks! shoot, i meant to file this in the `markdownlint` project, not the vscode extension :( sorry about that! thanks for the support
