### ISSUE TITLE
cmd + b is already a defualt VsCode keybinding

### ISSUE THREAD

**Issue by dannyknows** [DavidAnson/vscode-markdownlint#225]
Just wanted to mention, the extensions default `toggle bold` keybinding conflicts with VsCode's default `toggle side bar visibility` keybinding `cmd + b`. 

I simply disabled the extensions keybinding because my muscle memory is already used to `cmd + b` for something else.

**Comment by DavidAnson** [comment]
This extension does not configure any key bindings.

**Comment by DavidAnson** [comment]
Nor does it implement either of those behaviors.

**Comment by dannyknows** [comment]
Very true, my apologies. [This](https://github.com/yzhang-gh/vscode-markdown) was the culprit

**Comment by DavidAnson** [comment]
Cool, I'll try to remember if this comes up again!

**Comment by dannyknows** [comment]
Someone has already [raised it](https://github.com/yzhang-gh/vscode-markdown/issues/995) too 🤦
