### ISSUE TITLE
MD024/no-duplicate-heading/no-duplicate-header shows even though these are headings with different parent headings

### ISSUE THREAD

**Issue by piejanssens** [DavidAnson/vscode-markdownlint#227]
In a [common changelog format](https://keepachangelog.com/en/1.0.0/) the following structure will be present:

```
# Changelog

All notable changes to this project will be documented in this file.

## [1.1.0]

### Changed

- some change here

### Fixed

- small fix here

## [1.0.1]

### Changed

- older change here
```

markdownlint is currently reporting `MD024/no-duplicate-heading/no-duplicate-header: Multiple headings with the same content` on the second `### Changed` even though it's below a different ##-level header.

**Comment by nschonni** [comment]
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024 there are options for that style
