### ISSUE TITLE
Disable the bulb icon

### ISSUE THREAD

**Issue by tylerwince** [DavidAnson/vscode-markdownlint#23]
Is there any way to disable the lightbulb icon and just have the errors underlined?

I find the bulb to be distracting and would prefer the more subtle warning especially when I am typing longer documents and will go back to reformat afterward.

**Comment by DavidAnson** [comment]
The light bulb icon is provided by VS Code. I don’t know a way to opt out as an extension, but I’ll look. You might also check the list of user settings in the app for a way to customize this and open an issue for VS Code if you don’t find anything.

**Comment by DavidAnson** [comment]
Doing a quick bit of research, it seems there is a good bit of discussion about how the light bulb should behave: https://github.com/Microsoft/vscode/issues/25174

But it looks like they may already have a way to disabled it like you want: https://github.com/Microsoft/vscode/pull/33982

**Comment by DavidAnson** [comment]
Seems like you want to set `editor.lightbulb.enabled` to `false` per the section “Lightbulb improvements” here: https://code.visualstudio.com/updates/v1_17

**Comment by tylerwince** [comment]
Thanks @DavidAnson. And thanks for the markdownlint extension, incredibly useful!
