### ISSUE TITLE
Markdownlint extension having trouble with new Local History feature

### ISSUE THREAD

**Issue by gregvanl** [DavidAnson/vscode-markdownlint#236]
VS Code Version: 1.66.0
OS Version: Windows 11

Steps to Reproduce:

1. Install the Markdownlint extension https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
2. With Local History enabled in the Timeline view (default for 1.66), open a Markdown file and begin making changes.
3. Click on a File Saved entry.

The Markdownlint extension starts sending text to the Output panel.

[4:17:22 PM] ERROR: Exception while linting with markdownlint-cli2:
SyntaxError: Unexpected number in JSON at position 1
at JSON.parse ()
at c:\Users\gregvanl.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:4010
at c:\Users\gregvanl.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:4879
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
at async c:\Users\gregvanl.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:8417
at async T (c:\Users\gregvanl.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:37:8359)
[4:17:22 PM] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse 'c:/Users/gregvanl/vscode-docs/release-notes/.markdownlint.jsonc'; Parser 0: Unexpected number in JSON at position 1; Parser 1: Source contains multiple documents; please use YAML.parseAllDocuments()
at c:\Users\gregvanl.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:33:29570
at c:\Users\gregvanl.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.46.0\bundle.js:1:2260
at processTicksAndRejections (node:internal/process/task_queues:96:5)

If you try to close the Output panel, it pops back open. Reloading the window stops the output briefly but the Output panel opens again.

If you select a Git History item, Markdownlint stops the output.

**Comment by DavidAnson** [comment]
The exception text makes it sound like there is an issue with the configuration file:
```
Error: Unable to parse 'c:/Users/gregvanl/vscode-docs/release-notes/.markdownlint.jsonc'; Parser 0: Unexpected number in JSON at position 1; Parser 1: Source contains multiple documents; please use YAML.parseAllDocuments()
```

Could you please share the content of that?

**Comment by gregvanl** [comment]
There is no .markdownlint.jsonc file in the repo. 
As I open different files in different folders in the repo, the path in the output changes.
It looks like it is trying to find that configuration file in the folder for the file with local changes.

**Comment by DavidAnson** [comment]
Sounds like it's looking for configuration files and VS Code or an extension is lying about their presence/content.

Are you using this extension for local history? https://marketplace.visualstudio.com/items?itemName=xyz.local-history

Does the problem happen if you disable that extension and restart?

**Comment by gregvanl** [comment]
Nope, I don't have the xyz.local-history extension installed. This happens with the new built-in Local History feature shipped in VS Code 1.66, no extension required.
I can repro on 1.66 Stable (just released today) with only the Markdownlint extension installed.
Here's the release notes about the Local History feature, which has some information about its backend storage.
https://code.visualstudio.com/updates/v1_66#_local-history

**Comment by DavidAnson** [comment]
Thanks! I can reproduce this and hope to publish a fix soon. See the discussion in #230 for the cause.

**Comment by DavidAnson** [comment]
Please try the updated version I published last night. I believe it should address this.

**Comment by gregvanl** [comment]
Works great again! Thank you for such a prompt response
