### ISSUE TITLE
[Feature Request] Support gitlab table-of-contents syntax

### ISSUE THREAD

**Issue by vonBork** [DavidAnson/vscode-markdownlint#237]
Gitlab supports a table of contents syntax to create them in Markdown Wiki Pages. It would be great if your Plugin could support them. It's eather `[[_TOC_]]` or `[TOC]`.  For more information have a look at https://docs.gitlab.com/ee/user/markdown.html#table-of-contents and https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/user/markdown.md#table-of-contents

It shouldn't be to dificult to search every line starting with a `#` and indenting these headlines depending on the number of  hash signs in front of them.

What do you think about it?

My Environment:
OS: Windows
markdownlint: v.47.0
Visual Studio Code: 1.66.0

Thanks in advance.

**Comment by DavidAnson** [comment]
What support are you asking for? Here's the TOC example from the link you provide - it already lints cleanly as far as I can tell:

```markdown
This sentence introduces my wiki page.

[[_TOC_]]

## My first heading

First section content.

## My second heading

Second section content.
```

**Comment by vonBork** [comment]
But it isn't resolving the Table of Content. 
![image](https://user-images.githubusercontent.com/36640531/163649373-1229fbb7-981d-438c-acb7-81a7f2064628.png)

It would be nice if the TOC would look somethink like this.

![image](https://user-images.githubusercontent.com/36640531/163649566-36c191ef-5a59-4a22-ad95-59134bafdd79.png)

**Comment by DavidAnson** [comment]
This extension does not do play a role in rendering the preview for Markdown content. The core of that is done by VS Code itself and there may be extensions that offer services like what you are looking for here.

**Comment by vonBork** [comment]
Oh I'm sorry. Your extension is the only markdown extension in my VS Code, so I thought the preview is provided by you.
Then I have to look somewhere else. Any chance you do happen to know which repo is the right one?

By the way you can close this issue.

**Comment by DavidAnson** [comment]
A very quick search didn't turn up an extension to do this, so you might check the VS Code issue tracker itself. Maybe someone else has already asked for this or maybe you are the first one!

**Comment by vonBork** [comment]
I foud it myself in the vscode repository. It is an extension bundled with vscode. https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features The Link in the Readme describes the Preview Feature. In case someone is curious.
