### ISSUE TITLE
Linter is incorrectly recognised by VSCode as a formatter

### ISSUE THREAD

**Issue by wolf99** [DavidAnson/vscode-markdownlint#243]
I noticed this morning that VSCode has started showing me this for markdown files that I edit:

![image](https://user-images.githubusercontent.com/281700/173800593-bca52ffb-13c4-4971-a9b5-cb4d731091a3.png)

This is because I have two extensions related to markdown installed and enabled. If I click the configure in the above image, I see the following:

![image](https://user-images.githubusercontent.com/281700/173800878-fc11c6b4-e8a7-4dc6-98ec-bf9f65a8224c.png)

To me this is because VSCode thinks that this extension is a formatter, where actually it is a linter.
The difference being that a formatter makes changes to a file as you type, whereas a linter points out mistakes (but does not remedy them itself).

Is there some way that this extension can indicate this difference to the IDE?

(If there is no method to do this in VSCode then this is actually an issue on VSCode rather than this extension)

**Comment by wolf99** [comment]
Hmmm. That's a fair enough explanation. 

But at the same time, this `fix` functionality will only fix lint issues, correct?
It doesn't, and I don't propose that it should, format all the many things the other extension does. (And vice versa)

Thus maybe this is a feature request to vscode to allow multiple formatters to work together... What do you think?

**Comment by DavidAnson** [comment]
Right, each extension will only fix the issues it knows about. It looks like Code is encouraging you to pick one as the default, but I believe it will still allow you to run either or both if you wish.
