### ISSUE TITLE
fixing MD034 moves cursor into wrong/awkward position

### ISSUE THREAD

**Issue by zzzz465** [DavidAnson/vscode-markdownlint#251]
fixing MD034 using `fix on save` set cursor to a awkward position.

## 1. when the cursor is positioned newline after a link
the cursor moves into a link and makes a selection from it to the next newline

### before
![image](https://user-images.githubusercontent.com/46273764/188254781-00e03459-9d1c-4e24-aa79-5f0f5fb14225.png)

### after
![image](https://user-images.githubusercontent.com/46273764/188254824-0983f3ab-8c14-415d-88f8-1edcdac79d3c.png)

### expected
![image](https://user-images.githubusercontent.com/46273764/188255121-6d1ee039-2412-4f1b-bacb-fbba52117aa0.png)

## 2. when the cursor is positioned on the link
the cursor doesn't move to the end, which makes it awkward to edit forward.

### before
![image](https://user-images.githubusercontent.com/46273764/188254830-f882bd70-4243-42ed-8287-068c5e14dbfa.png)

### after
![image](https://user-images.githubusercontent.com/46273764/188254833-6f2f7168-dadb-40a5-a7a6-06662200df13.png)

### expected
![image](https://user-images.githubusercontent.com/46273764/188255128-3c18d321-9840-41a0-8322-aa5fd5299111.png)

**Comment by DavidAnson** [comment]
Sounds very similar to: https://github.com/DavidAnson/vscode-markdownlint/issues/159

I’ll have a look, but I may not be able to coax  the right behavior out of VS Code.

**Comment by DavidAnson** [comment]
This works correctly for me on VS Code 1.74.2 (Mac) with markdownlint 0.48.1. Specifically, with `"editor.formatOnSave": true` active, your scenario 1 behaves as you expect with the cursor remaining on the line after the link and your scenario two leaves the cursor between the "o" and "m". (Note that scenario 2 with the cursor after the "m" results in the cursor being after the ">", but this makes sense as it stays at the end of the line. Putting the cursor anywhere in ".com" keeps it where it as as you want.
