### ISSUE TITLE
How to automatically open md file with VSC+Markdownlint Editor

### ISSUE THREAD

**Issue by coisox** [DavidAnson/vscode-markdownlint#254]
Sorry if this is not the correct place to ask. I couldn't find in Wiki or during installation.

I want to double click **.md** file from Windows Explorer and it will auto open **VSC + Markdownlint Editor**, not the source code editor. Currently I can auto open in VSC but I have to press **CTRL+SHIFT+P** and choose **"markdown-editor: Open with markdown editor"**

Is it possible and how?

**Comment by DavidAnson** [comment]
The command you show ("markdown-editor") is not provided by the markdownlint extension. You may find an answer in the docs for that editor or the VS Code Docs here: https://code.visualstudio.com/docs/languages/markdown

**Comment by coisox** [comment]
So "markdown-editor" is not came from markdownlint? What editor (or how to access) for markdownlint? Sorry again if this sounds so noob. I really not familiar with the terminology

**Comment by coisox** [comment]
I think I'm starting to understand. If the command coming from markdownlint, it should be "markdownlint: Do something" right?

**Comment by DavidAnson** [comment]
Right. Check the extensions you have installed, maybe disable them one-by-one to find when that command disappears. I don't think it's a built-in VS Code thing.

**Comment by coisox** [comment]
Thank you sir.
