### ISSUE TITLE
Keyboard shortcut (format the document) in README.md should call out Linux-specific chord

### ISSUE THREAD

**Issue by peter-kehl** [DavidAnson/vscode-markdownlint#255]
Dear David,

Thank you so much for VS Code Markdown Lint. So ergonomic.

README.md says "Shift+Alt+F" (to format the document). But my (current) VS Code 1.71.2 (as shipped/packaged) on current Manjaro Linux (GNOME 42.4) uses Ctrl+Shift+I instead (and Shift+Alt+F doesn't seem to do anything). I do have many VS Code extensions installed, but otherwise standard VS Code installation (and I'm not a VS Code guru - if you'd like me to investigate anything, please advise).

I don't have Mac OS. I confirm that Ctrl+K Ctrl+F does format a code selection (on Linux) as per README.md.

**Comment by DavidAnson** [comment]
It looks like that command uses F on Windows and Mac and I on Linux: https://code.visualstudio.com/docs/editor/codebasics#_formatting

I conventionally offer the Windows and Mac shortcuts in the documentation, assuming Linux matches Windows.

I can update this particular section to call out that Linux is different.

**Comment by peter-kehl** [comment]
Yes please. Thank you in advance.
