### ISSUE TITLE
Add a link to Line Length Checker

### ISSUE THREAD

**Issue by peter-kehl** [DavidAnson/vscode-markdownlint#258]
I like all Markdown Lint checks/features. I love `MD013/line-length` even more so (because I vary screens, vertical splits, show/hide the navigator/gutter...). So I hoped to find a similar line length checker for other file types, too. And I did find one.

To save other Markdown Lint users' time, please consider adding something like the following to `README.md`:

If you use ``MD013/line-length`, you may like [SUPERTSY5.line-length-checker-vscode](https://marketplace.visualstudio.com/items?itemName=SUPERTSY5.line-length-checker-vscode) ([supertsy5/line-length-checker-vscode](https://github.com/supertsy5/line-length-checker-vscode)). And if you use them together and you want to disable `SUPERTSY5.line-length-checker-vscode` for Markdown files, have this in your `settings.json`:
```
{
...
"line-length-checker.blacklist": [
        "**/*.md"
    ],
...
}
```

Thank you in advance for considering. Of course, feel free to modify as you see fit.

**Comment by nschonni** [comment]
Since that extension only has 91 installs, I don't think there are a lot of people running into this

**Comment by DavidAnson** [comment]
In general, I link to other projects that use this library, but I don't tend to recommend anything else. Prettier gets mentioned a few times because it generates compatibility issues and questions.
