### ISSUE TITLE
markdownlint.json not being found

### ISSUE THREAD

**Issue by stephaniehobson** [DavidAnson/vscode-markdownlint#26]
This extension is great. I'm migrating my blog to markdown right now and it has been super useful!

I want to ignore a few chronic problems with my content but I can't get `.markdownlint.json` working.

My `.markdownlint.json` file looks like this:

```
{
  "default": true,
  "MD026": {
    "punctuation": ","
  }
}
```

It is located in:
```/Users/stephaniehobson/public/sites/blog_hexo```

The output console says:
```
[12:17:58] INFO: Loading user/workspace configuration for '/Users/stephaniehobson/Public/Sites/blog_hexo/source/_posts/a-matter-of-semantics.md' (no configuration file in workspace folder).
```

I opened the file by going:
**File** > **Open** > and picking **blog_hexo** from the list. Then I used the file explorer to browse the sub-directories and find the file. 

I appreciate any help. Thanks!

**Comment by DavidAnson** [comment]
Cool, glad it helps! :)

For the issue, please reread this section: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#configure

Bare files don’t have a workspace, but if you open the `blog_hexo` folder instead, your customizations should be applied to all files within.

**Comment by DavidAnson** [comment]
Explicitly: File menu, Open Folder, blog_hexo

**Comment by stephaniehobson** [comment]
That's what I did :(

(Well, there is no "Open Folder" option so I used "Open" and then picked the folder and opened it).

**Comment by DavidAnson** [comment]
The menu option looks like this:

![openfolder](https://user-images.githubusercontent.com/1828270/35188774-56bc11ee-fdf1-11e7-919c-3b710d34e1a1.png)

**Comment by stephaniehobson** [comment]
Sorry, should have mentioned, I'm on a Mac.

Here is what I'm doing:
![screen shot 2018-01-21 at 12 38 32](https://user-images.githubusercontent.com/854701/35189079-38a59718-fea8-11e7-9393-46ff27ff14cf.png)
![screen shot 2018-01-21 at 12 38 53](https://user-images.githubusercontent.com/854701/35189081-3cee10de-fea8-11e7-9e9d-f75b1b922fe4.png) 
(Then clicking open)
![screen shot 2018-01-21 at 12 39 33](https://user-images.githubusercontent.com/854701/35189082-40587c1e-fea8-11e7-890b-787af1a8a4a1.png)

It's the same process I use for opening a project with Atom or Sublime but I'm new to VS Code (3 whole days!) so I don't know it as well.

**Comment by stephaniehobson** [comment]
PS - thanks for replying on a weekend :)

**Comment by stephaniehobson** [comment]
And here's the whole menu. No Open Folder :(

![screen shot 2018-01-21 at 12 57 19](https://user-images.githubusercontent.com/854701/35189204-b34b760c-feaa-11e7-9353-8a171220c44d.png)

**Comment by DavidAnson** [comment]
Huh. I don’t have a Mac, but what you’re doing sounds right and the folder hierarchy image suggests it’s open as a folder. Is there a chance this repository is public so I can clone and try locally?

**Comment by DavidAnson** [comment]
Ok, I was misinterpreting the message. The extension realizes there is a workspace (I.e., folder open). Sorry for the goose chase. But it is not finding the file. If public, please share, if not, can you please show the output of `ls` to confirm the name/location of `.markdownlint.json`?

**Comment by stephaniehobson** [comment]
```
125-236-213-109:blog_hexo stephaniehobson$ ls -a
.			.editorconfig		.markdownlint.json 	_config.yml		package-lock.json	scaffolds
..			.eslintrc.js		.stylelintrc		db.json			package.json		source
.DS_Store		.gitignore		.vscode			node_modules		public			themes
```

It's not a repo yet but I can duplicate the folder, remove the not-public stuff, and publish to git if that's the next step debugging it.

**Comment by DavidAnson** [comment]
Still looks right, sorry for the trouble.  Instead of you publishing before you are ready, let me publish a repo to demonstrate how this works. I’ve wanted this for others before now anyway. You can clone it and let me know if it works for you. If so, then we find the difference for your scenario. If not, then I buy a Mac and debug. :)

**Comment by stephaniehobson** [comment]
OMG I found the problem committing the files to git... there was a space at the end of the file name 😫

Thank you so much for the help. I'm sorry for the trouble.

**Comment by DavidAnson** [comment]
Woot! Thanks for sharing - you saved me a bit of time just now. :)

Please let me know if you have any other issues/suggestions.
