### ISSUE TITLE
Prevent behavior - adding comma after numbers

### ISSUE THREAD

**Issue by cspenn** [DavidAnson/vscode-markdownlint#267]
In linting, the plugin performs the following undesirable behavior:

123,456 becomes 123, 456

How do I prevent it from adding that space after the comma?

**Comment by nschonni** [comment]
I don't think that's this plug-in. It sounds more like a prettier thing

**Comment by DavidAnson** [comment]
Agreed that's not something this extension does, you can see here your example does not produce any warnings: https://dlaa.me/markdownlint/#%25m%23%20Issue%20267%0A%0A123%2C456%0A

**Comment by cspenn** [comment]
Thank you - where would I go to hunt down this behavior and repair it?

**Comment by DavidAnson** [comment]
I'd suggest disabling extensions one at a time. I don't think this is VS Code behavior, so it seems likely to come from something you've added.

**Comment by cspenn** [comment]
It was a conflict with mervin's markdown formatter! Thanks all.
