### ISSUE TITLE
frontMatter ignore

### ISSUE THREAD

**Issue by davidlaym** [DavidAnson/vscode-markdownlint#27]
How do I set markdown lint's `options.frontMatter` on .markdownlint.json?

https://github.com/DavidAnson/markdownlint#optionsfrontmatter

I'm getting all kind of validation error for lists and spacing and headers inside the frontmatter that should not trigger.

**Comment by DavidAnson** [comment]
`.markdownlint.json` is only for configuring rules. The default setting for `frontMatter` works for most scenarios. Can you give a small example of what’s not working for you?

**Comment by davidlaym** [comment]
I was able to narrow it down to the specific case in which the file has only a front matter and no other content, so this may be actually a problem with markdownlint itself.
Actually, it's enough to add two new lines at the end of the frontmatter to trigger the correct linting.

Thanks for the quick answer!

**Comment by DavidAnson** [comment]
Glad you sorted it out! If you want to share an example, I’m still curious if it could be handled better.
