### ISSUE TITLE
Error: Cannot find module 'markdownlint-rule-search-replace'

### ISSUE THREAD

**Issue by notJoon** [DavidAnson/vscode-markdownlint#270]
Recently, this error has begun to appear. 

Additionally, the output window is fixed and cannot be moved to another tab, such as a `terminal` or `problems` (I'm not sure is related to this error). 

I checked #158, #264 and re-installed but it didn't work.

```plain
[11:23:51 PM] ERROR: Exception while linting with markdownlint-cli2:
Error: Cannot find module 'markdownlint-rule-search-replace'
Require stack:
- /Users/user/.vscode/extensions/davidanson.vscode-markdownlint-0.48.1/bundle.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js / Invalid host defined options
    at w (/Users/user/.vscode/extensions/davidanson.vscode-markdownlint-0.48.1/bundle.js:37:6800)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at T (/Users/user/.vscode/extensions/davidanson.vscode-markdownlint-0.48.1/bundle.js:37:9515)
    at L (/Users/user/.vscode/extensions/davidanson.vscode-markdownlint-0.48.1/bundle.js:37:13852)
```

**Comment by DavidAnson** [comment]
It seems like one of the configuration files in your project is referencing that custom rule, but the rule is not available. As with the other issues you've linked to, you could remove the reference to that custom rule from configuration (which may be in a file or user/workspace configuration) or you can make that rule available (typically by adding the code to the project). Your inability to move the VS Code input window should have nothing to do with this, but you can temporarily disable the markdownlint extension in the extensions tab if you want to be sure of that.

**Comment by nschonni** [comment]
@notJoon since i'm guessing you're hitting this in the mdn/translated-content repo, you need to run `yarn` to install the missing dependency

**Comment by notJoon** [comment]
@DavidAnson @nschonni Oh, It was a missing dependency problem. thanks for your help
