### ISSUE TITLE
Stopped linting/reformatting json code blocks

### ISSUE THREAD

**Issue by r-this** [DavidAnson/vscode-markdownlint#272]
For some reason it stopped automatically cleaning up json code blocks on save. It will still do it if I Force Reformat on the page. It is still doing the other automatic formatting, eg it will automatically remove a ':' from the end of a heading which Prettier will not, so I'm pretty sure it's markdownlint doing it. There are no messages popping up in dev console or Output when I save with the unformatted json. 

I know it's pretty vague. Tried to search for others who've encountered similar issues. Let me know if you have any ideas. Thanks!

**Comment by nschonni** [comment]
Markdownlint has never formatted code blocks, that would have been prettier or another extension

**Comment by DavidAnson** [comment]
Glad you got this sorted out, thank you for the detailed explanation! I wish the automatic formatting stuff were a little more obvious in VS Code because I've had questions about this before and not everyone is aware of the settings and configuration like you are.
