### ISSUE TITLE
How do I set global settings using a .cjs file

### ISSUE THREAD

**Issue by leoseccia** [DavidAnson/vscode-markdownlint#279]
How can I use my .markdownlint-cli2.cjs for all my projects without having to copy it at the root of every project?

**Comment by DavidAnson** [comment]
If you want to share settings in the VS Code environment, you can use its user settings infrastructure like so: https://github.com/DavidAnson/vscode-markdownlint#markdownlintconfig

That doesn't allow customizing everything you can do with your current CJS configuration file, however.

If it's just a question of not duplicating things, you could have every project include a single-line CJS configuration file that require-s a common file which contains all the configuration.

But if you don't want to put ANY configuration file in your project and you don't want to use Code settings, I don't know of a great way to do that today.

**Comment by leoseccia** [comment]
Thank you David. I will try that. 
Awesome plugin BTW :-)
