### ISSUE TITLE
Differentiated config based on path

### ISSUE THREAD

**Issue by simensol** [DavidAnson/vscode-markdownlint#280]
I want to use markdownlint for linting `*.md` files from VitePress. With VitePress, one is able to [include Vue code inside the markdown](https://vitepress.dev/guide/using-vue). Thus, when linting VitePress `*.md` files, I want to disable for example [`MD033`](https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md) and [`MD041`](https://github.com/DavidAnson/markdownlint/blob/main/doc/md041.md). However, I also have regular `*.md` files (e.g. GitHub `README.md` files) where I don't want to disable these rules. Is it a way to configure markdownlint to apply different rules to different paths?

**Comment by DavidAnson** [comment]
Yes, you can specify different configuration at each level of the directory tree: https://github.com/DavidAnson/markdownlint-cli2#configuration
