### ISSUE TITLE
New version of markdownlint breaks other extensions due to unresponsive extension host error

### ISSUE THREAD

**Issue by scottmc42** [DavidAnson/vscode-markdownlint#287]
Setup:
VS Code Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:31:03.317Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

markdownlint extension (0.50.0)

After the recent update, when I have the markdownlint extension enabled, other extensions stop working.

As an example, I also have markdown table installed. When I try to tab to the next cell in a markdown table, it just inserts tabs instead. Another example is that files that are under git control no long have the visual effects of a git control file (green filename for new, orange for modified existing file, etc).

Looking at Developer Tools it reports:
WARN UNRESPONSIVE extension host: 'davidanson.vscode-markdownlint' took 98.12524587504343% of 4911.25ms, saved PROFILE here: 'file:///var/folders/qy/r3x9hxjx1bscyym68nz12f7m0000gp/T/exthost-105601.cpuprofile'

When I disable markdownlint, everything else starts working again.

Attached in the full javascript log for the error:
[vscode-app-1686621763315.log](https://github.com/DavidAnson/vscode-markdownlint/files/11729950/vscode-app-1686621763315.log)

**Comment by DavidAnson** [comment]
Sorry for the trouble! This sounds like #286. A new release of the extension should be out soon that addresses the extreme slowdown from tables you are experiencing with the current version.
