### ISSUE TITLE
Separate no-multiple-blanks from no-multiple-blanks-at-end-of-file

### ISSUE THREAD

**Issue by jkpubsrc** [DavidAnson/vscode-markdownlint#29]
no-multiple-blanks enables checks for multiple empty lines in a file. Unfortunately it is sometimes quite convenient to have multiple blank lines at the end of files. It would be great if the linter could distinguish between these final lines and multiple lines within the document. Then I could allow multiple blank lines at the end of a document but get warnings for multiple blank lines in the rest of the document.

**Comment by DavidAnson** [comment]
What are some scenarios where having multiple blank lines at the end of a file is helpful?

**Comment by DavidAnson** [comment]
Closing for lack of a scenario.
