### ISSUE TITLE
MD029 bug

### ISSUE THREAD

**Issue by IamRezaMousavi** [DavidAnson/vscode-markdownlint#292]
It's correct but markdownlint say it's wrong
![Screenshot from 2023-07-22 15-58-22](https://github.com/DavidAnson/vscode-markdownlint/assets/83984878/7bbaa2b9-cb8e-462e-a8d9-dc3b9315c6da)

**Comment by DavidAnson** [comment]
The syntax you show above where the code fences are not fully indented to match the list item content (three spaces are required) creates two separate lists. The second list's item does not begin with the number one, so the reported MD029 violation is correct.

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20Issue%20292%5Cn%5Cn1.%20List%5Cn%5Cn%20%20%60%60%60%5Cn%20%20Code%5Cn%20%20%60%60%60%5Cn%5Cn2.%20List%5Cn%5Cn%20%20%60%60%60%5Cn%20%20Code%5Cn%20%20%60%60%60%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

**Comment by IamRezaMousavi** [comment]
See the code:
https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/blob/f1ce6fcc0e41af4a1ac3f94273a2b6b988f62b33/README.md?plain=1#L45C1-L55C6

**Comment by IamRezaMousavi** [comment]
See
https://github.com/IamRezaMousavi/persian-gnome-calendar-extension/blob/f1ce6fcc0e41af4a1ac3f94273a2b6b988f62b33/README.md?plain=1#L45-L55

**Comment by DavidAnson** [comment]
That appears to be the same scenario. Indent the code fences three spaces to be properly within the list items and the warning will go away because it will become a single list as intended.

**Comment by IamRezaMousavi** [comment]
I used `three spaces` instead of `a tab` and warning is disappeared
But I think it should not warn for tab, btw

**Comment by DavidAnson** [comment]
The code you link to above in GitHub appears to use two space characters, not a tab character. That's also how VS Code is configured in the screenshot above ("Spaces: 2").

If tab characters are used in this scenario, the MD029 warning is not presented as you wish: https://dlaa.me/markdownlint/#%25m%23%20Issue%20292%0A%0A1.%20List%0A%0A%09%60%60%60text%0A%09Code%0A%09%60%60%60%0A%0A2.%20List%0A%0A%09%60%60%60text%0A%09Code%0A%09%60%60%60%0A
