### ISSUE TITLE
LoiMr

### ISSUE THREAD

**Issue by ngocloi93** [DavidAnson/vscode-markdownlint#293]
Type: <b>Performance Issue</b>

LoiMr

Extension version: 0.51.0
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.18363
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz (16 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (25.26GB free)|
|Process Argv|--open-url --crash-reporter-id 06a17c7c-de0e-4193-921d-4d88a1c0e087 -- vscode://github.codespaces/connect?name=ngocloi93-obscure-space-potato-jj5j69rqvvw9cgx5&windowId=_blank|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	  9444	code main
    3	   121	  2776	extensionHost [1]
    0	    14	  9260	   crashpad-handler
    0	    44	 10408	ptyHost
    0	   132	 10520	shared-process
    0	    28	 10596	   utility-network-service
    0	   344	 11200	window [1] (Welcome - Visual Studio Code [Administrator])
    0	    98	 11932	   gpu-process
    0	    41	 12356	fileWatcher [1]
    0	    59	 12576	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
ecj1e332:30736112
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by ngocloi93** [comment]
ok

**Comment by DavidAnson** [comment]
Please see issue #291 for next steps. When you run the bisect, you may find the responsible extension is not this one. But if it is, then I need a link to the CPU profile in order to investigate. Thank you.

**Comment by DavidAnson** [comment]
Closing for lack of action/data.
