### ISSUE TITLE
Linter broken with error "Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'"

### ISSUE THREAD

**Issue by deadlydog** [DavidAnson/vscode-markdownlint#296]
A few weeks ago I noticed that the markdown linter stopped working in VS Code, and it is outputting the following error in the `OUTPUT` window whenever I view a markdown file:

```text
[10:38:34 AM] ERROR: Exception while linting with markdownlint-cli2:
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
    at w (c:\Users\Dan.Schroeder\.vscode\extensions\davidanson.vscode-markdownlint-0.51.0\bundle.js:37:6909)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at L (c:\Users\Dan.Schroeder\.vscode\extensions\davidanson.vscode-markdownlint-0.51.0\bundle.js:37:9738)
    at D (c:\Users\Dan.Schroeder\.vscode\extensions\davidanson.vscode-markdownlint-0.51.0\bundle.js:37:14195)
```

I've tried uninstalling and reinstalling the extension, but the problem persists.

I'm using v0.51.0 of [the markdownlint extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint), and here is my VS Code info:

```text
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

Any idea what is wrong, or troubleshooting steps I can take to get you more info? Thanks.

**Comment by DavidAnson** [comment]
Duplicate of external issue <https://github.com/DavidAnson/vscode-markdownlint/issues/264>. Steps to fix are linked there.

**Comment by deadlydog** [comment]
Ah, I had only searched Open issues so I didn't find that one. Thanks for the link. Removing the setting [as suggested in the fix](https://github.com/DavidAnson/vscode-markdownlint/issues/158#issuecomment-1201424630) worked 👍
