### ISSUE TITLE
update of markdownlint-cli2

### ISSUE THREAD

**Issue by eUgEntOptIc44** [DavidAnson/vscode-markdownlint#303]
Hi @DavidAnson 

I just discovered the latest (0.10.0) release of [`markdownlint-cli2`](https://github.com/DavidAnson/markdownlint-cli2).

I understand that a new release of the VS code extension would be required to use the new release of the cli.

I'm stilly pretty new to this project and might have missed something. I'd be very grateful if you could share some insights on this.

**Comment by eUgEntOptIc44** [comment]
Thanks for sharing this. 👍

**Comment by DavidAnson** [comment]
Version `0.52.0` of the VS Code extension has just been published to the marketplace.
