### ISSUE TITLE
Docs, `MD024`: explain difference between `allow_different_nesting` and `siblings_only`

### ISSUE THREAD

**Issue by bersbersbers** [DavidAnson/vscode-markdownlint#305]
Currently, both parameters have the same explanation,  "Only check sibling headings":

> allow_different_nesting: Only check sibling headings (boolean, default false)
> siblings_only: Only check sibling headings (boolean, default false)

**Comment by bersbersbers** [comment]
I just see below this:
> If the parameter siblings_only (alternatively allow_different_nesting

Does this mean the two parameters are aliases?

**Comment by DavidAnson** [comment]
Right, they do the same thing. One is provided for compatibility and the other for clarity.
