### ISSUE TITLE
Output keeps stealing focus from terminal if dependencies aren't installed

### ISSUE THREAD

**Issue by Jamesernator** [DavidAnson/vscode-markdownlint#309]
Trying to open the terminal when markdownlint doesn't have the required dependencies keeps focusing the output tab:

[Screencast from 18-11-23 18:03:14.webm](https://github.com/DavidAnson/vscode-markdownlint/assets/8518303/b5400b1d-058e-46d4-b69d-37a2f86187cc)

Yes I can open a terminal outside of VSCode so it's easy to workaround, but I don't see why opening a terminal should trigger markdownlint to steal focus back in the first place.

**Comment by DavidAnson** [comment]
The tool is trying to call your attention to the fact that the current configuration is broken and linting cannot be performed. The assumption is that you will want to fix or remove that configuration. Is there a reason that's not possible in your scenario?

**Comment by Jamesernator** [comment]
> Is there a reason that's not possible in your scenario?

Like I said

> Yes I can open a terminal outside of VSCode so it's easy to workaround,

But this is somewhat annoying as I've hit this problem quite a number of times where I went to make an edit in a project but hadn't installed the project yet.

**Comment by DavidAnson** [comment]
I suppose I could do something to limit the number of times focus is set. But I don't think removing notifications and allowing things to fail silently in the background is what most people want.

**Comment by Jamesernator** [comment]
> But I don't think removing notifications and allowing things to fail silently in the background is what most people want.

Is there any reason not to show [*actual notifications*](https://code.visualstudio.com/api/ux-guidelines/notifications) rather than just stealing focus?

That is what other tools like TypeScript do if there is a warning or such:

![Screenshot from 2023-11-18 20-40-45](https://github.com/DavidAnson/vscode-markdownlint/assets/8518303/e740a3a2-e531-446b-bfc7-4b438989b476)

**Comment by DavidAnson** [comment]
Notifications have much less room to show information and are often not copyable. Besides, I don't think you'd be happy with a steady stream of notifications, either.

Thinking about this issue last night, I decided it would probably be sufficient to focus the output window once per session - and again on any configuration change. That should alert users to the problem and show them where to get the information they need to diagnose it and help them troubleshoot when they are making fixes - while not getting too much in the way of people who choose to work with broken configuration.
