### ISSUE TITLE
Allow 2 trailing whitespace by default

### ISSUE THREAD

**Issue by spawnia** [DavidAnson/vscode-markdownlint#31]
I propose to include the setting for trailing whitespace to allow for exactly 2 spaces. The default rule just makes little sense for Markdown, considering the 2 trailing spaces are part of the syntax.

**Comment by DavidAnson** [comment]
Do you think this request is specific to the VS Code implementation, or a general issue for the library and all it’s uses? If the latter, could you please open it here: https://github.com/DavidAnson/markdownlint

Thanks!

**Comment by spawnia** [comment]
You are right, this actually does concern the library as a whole. Will open the issue there, thank you.
