### ISSUE TITLE
Discussion: Command line run to enable in Jenkins

### ISSUE THREAD

**Issue by gerhardol** [DavidAnson/vscode-markdownlint#311]
This is a discussion, not an issue (discussions are not enabled for this repo).
I expect this issue to be closed.

The extension works fine.
I would like to use the extension configuration in the CI/CD flow too and check files in Jenkins flow and maybe GitHub actions.
The executable must not be the same, but the configuration must be, at least being possible to convert the configuration in this extension to the configuration for the script to run in Jenkins (I expect to run a script added to a custom pipeline then a Jenkins plugin, that requires involving IT).

Any hints?

**Comment by DavidAnson** [comment]
It sounds like you want to invoke a CLI or GitHub Action that performs the same linting? Per the documentation, there are a few good options for that: https://github.com/DavidAnson/vscode-markdownlint#introduction
