### ISSUE TITLE
Disable Extension

### ISSUE THREAD

**Issue by Space-yg** [DavidAnson/vscode-markdownlint#329]
I am working in a workspace and I would like to disable the extension for this workspace only. What has worked is adding the following to the `settings.json`:
```json
"markdownlint.config": {
    "default": false
}
```
It would be nice if there was an `off` option in `markdownlint.run` to disable the extension completely.

**Comment by DavidAnson** [comment]
What you describe is a VS Code feature request. I do not think every extension should implement this individually. Your approach of disabling all rules seems effectively equivalent.

**Comment by Space-yg** [comment]
Sorry if I'm doing something wrong, I'm new to opening issues😅

**Comment by DavidAnson** [comment]
You didn't do anything wrong, I just don't think this is something that this extension (or others) should implement themselves.

**Comment by nschonni** [comment]
> I am working in a workspace and I would like to disable the extension for this workspace only. What has worked is adding the following to the `settings.json`:

https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension

**Comment by DavidAnson** [comment]
Thanks, Nick! I scanned that page yesterday, but missed that disable already worked per-workspace.
