### ISSUE TITLE
support ignore some files?

### ISSUE THREAD

**Issue by atian25** [DavidAnson/vscode-markdownlint#33]

**Comment by DavidAnson** [comment]
Can you give some more detail, please? Why ignore some files? What is special about them? Could `.markdownlint.json` be used?

**Comment by atian25** [comment]
prefer using vscode config rather than project file

```js
    "markdownlint.config": {
        "ignore": ["!**/History.md"],
        "MD013": false,
        "MD014": false,
    }
```

**Comment by DavidAnson** [comment]
Okay, thanks, something like that could work. But what is it about History.md that is special? Could you use inline comments instead to turn off some rules?

**Comment by DavidAnson** [comment]
Got it, thanks.

**Comment by donaldguy** [comment]
I would also just like to ignore some markdown files inside some vendored dependencies
