### ISSUE TITLE
Formatter functionality: adjust table size to its content

### ISSUE THREAD

**Issue by jerrygreen** [DavidAnson/vscode-markdownlint#330]
Here's what prettier does to tables:

![gif3](https://github.com/DavidAnson/markdownlint/assets/13215662/e755faff-6339-40da-a298-e29277056b3d)

But `markdownlint` can't do this, unfortunately. With `markdownlint`, the table remain still.

Coming from there:

- https://github.com/DavidAnson/markdownlint/issues/1159

**Comment by DavidAnson** [comment]
The referenced issue in markdownlint repository is the right place to track this.
