### ISSUE TITLE
could you please add a feature to add the 2 space at the end of each line if not given by default. 

### ISSUE THREAD

**Issue by OAtulA** [DavidAnson/vscode-markdownlint#331]
So when the line ends we need to add 2 spaces in the md format .  
But it would save some time if the extension could do it for us when we hit enter.  
After we save the file.

**Comment by DavidAnson** [comment]
Two spaces at the end of a line is known as a hard line break: https://spec.commonmark.org/0.31.2/#hard-line-breaks

This is not necessary, nor is it common in my experience. Are you suggesting otherwise?

**Comment by OAtulA** [comment]
Thanks for responding.
But when I write normally without adding 2 spaces at the end.

In the rendered page. I don't get the line break. They all come in one line.

**Comment by DavidAnson** [comment]
Yes. You should probably read about how Markdown formatting works. Blank lines introduce paragraphs. This page explains more: https://daringfireball.net/projects/markdown/syntax#p

**Comment by OAtulA** [comment]
But the point is not about creating paragraphs.
That's an easy thing to do.
I know that.

But my ask is to have 2 spaces at end of each line. When we save files.

Just like when I code in vs code in js.
It automatically adds the ; at the end of the line while I save. Maybe it's Prettier extension.
