### ISSUE TITLE
Possible to ignore line length for paragraphs?

### ISSUE THREAD

**Issue by jnobbe-palimpsest** [DavidAnson/vscode-markdownlint#338]
I'm using the [Foam extension](https://github.com/foambubble) for note taking. I'm wondering if it's possible to add a parameter to ignore paragraphs for rule MD013. I think otherwise I would need to add line breaks and write in a much different way to avoid the linter which would be counterproductive in this context. Is there another method I may not be thinking of?

**Comment by DavidAnson** [comment]
You can disable any rule. Various ways are shown in the README.

**Comment by jnobbe-palimpsest** [comment]
Hi David, thanks for the response. I was hoping to keep the length rule in place for other elements like code blocks. But then maybe it doesn't make sense to do that if any one thing is overflowing.

I'll dig into the readme some more and see if there was anything I missed.

________________________________

**Comment by DavidAnson** [comment]
Paragraph text is the easiest thing to wrap, so that forms the basis for the rule. You can opt things like code blocks, headings, and tables out and you can customize individual lengths, but the rule does not support opting paragraphs out other than disabling it entirely.

**Comment by jnobbe-palimpsest** [comment]
Thanks David, I've opted to disable this rule as you've suggested. I turned on vertical rulers for 80 and 120 characters as a reminder instead.
