### ISSUE TITLE
Unordered list is using asterisks but linter says dash is present.

### ISSUE THREAD

**Issue by KevDog** [DavidAnson/vscode-markdownlint#343]
I am getting the following error:
`[Unordered list style: role/tpm-role.md#L8](https://github.com/github/tpm/pull/2210/files#annotation_21736071893)
role/tpm-role.md:8:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]`

For this list, the error happens on the italicized line and continues for the next nine lines. Only line nine is part of a list.
* [IC levels](#levels-for-individual-contributors)
  * [TPM II](#tpm-ii)
  * [TPM III](#tpm-iii)
  * [Senior TPM](#senior-tpm)
  * [Staff TPM](#staff-tpm)
  * _[Principal TPM](#principal-tpm)_
* [Manager levels](#manager-levels)

**Comment by DavidAnson** [comment]
Could you please show the relevant Markdown?
