### ISSUE TITLE
MD013 line-length not automatically fixed by formatter

### ISSUE THREAD

**Issue by epneo-sebastianbaier** [DavidAnson/vscode-markdownlint#348]
Hi,

because of the issue #105 and your recommendation there:

> If you want the best compatibility between this extension and a CLI, you’ll have the easiest time using the markdownlint CLI written in/for Node.js: https://github.com/igorshubovych/markdownlint-cli

I'm now moving from `mdl` for `markdownlint-cli` for our pre-commit hooks. However, it seems the violations of MD013 line-length are not fixed automatically by the VSCode extension if used as formatter. Shouldn't this be automatically fixed, as written on the [VSCode extension page](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)?

> All of a document's violations of the above rules can be fixed automatically.

If I disable MD013 in my `.markdownlint.jsonc` it is no longer reported by the VSCode extension and the pre-commit is also not throwing an error, but if enabled both are recognizing the MD013 violation. So the configuration file is detected correctly by the VSCode extension and `markdownlint-cli`.

Greetings
Sebastian

**Comment by DavidAnson** [comment]
MD013 is not in the referenced list of rules that are automatically fixed.

**Comment by epneo-sebastianbaier** [comment]
Thx, I thought so and it was just a misunderstanding, because both lists (automatic fixable and not) are above the text:

> All of a document's violations of the above rules can be fixed automatically.

**Comment by DavidAnson** [comment]
I'll try to make this more clear in the documentation.

**Comment by ngdangtu-vn** [comment]
I was hoping that it could provide a hard wrapping solution...
