### ISSUE TITLE
file/folder exclusion is not working in 0.56.0

### ISSUE THREAD

**Issue by unional** [DavidAnson/vscode-markdownlint#351]
Hi, I notice file/folder exclusion is not working in 0.56.0.
It was working fine in 0.55.0.

I am using the `.markdownlintignore` file:

```
.changeset
**/CHANGELOG.md
```

I have also tried `markdownlint.lintWorkspaceGlobs`:

```jsonc
{
  "markdownlint.lintWorkspaceGlobs": [
    // ...
    "!**/.changeset",
    // or
    "!**/.changeset/*.md"
  ]
}
```

**Comment by unional** [comment]
I found that it works when using `.markdownlint-cli2.jsonc`.

is `markdownlint.lintWorkspaceGlobs` support also removed?

**Comment by DavidAnson** [comment]
Support for `.markdownlintignore` was deprecated in 55 and removed in 56 as part of `markdownlint.ignore`: https://github.com/DavidAnson/vscode-markdownlint/blob/main/CHANGELOG.md

The `lintWorkspaceGlobs` setting is only used when running the `lintWorkspace` command. This is implied by the name, but I realize the documentation is not clear about that and I will update it. https://github.com/DavidAnson/vscode-markdownlint?tab=readme-ov-file#workspace

**Comment by pgregory9** [comment]
Sorry to ask a basic question, but I've been looking around for an hour and cannot figure it out.

I want markdownlint to exclude/ignore any file with `*xx*` or `*test*` in the filename. So I had the following in my workspace `settings.json`

  ```
"markdownlint.ignore": [
    "*test*.md",
    "*Test*.md",
    "**/*test*.md",
    "**/*Test*.md",
    "*xx*.md",
    "**/*xx*.md"
  ],
```

This obviously is no longer working with the removal of `markdownlint.ignore`. How can I restore that behavior?

Thanks

**Comment by DavidAnson** [comment]
@pgregory9 The CLI2 configuration object has an `ignores` property that should work for this: https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#markdownlint-cli2jsonc

By adding a `.markdownlint-cli2.jsonc` file (or similar) to your project, you will get the exact same behavior from the VS Code extension (interactive) as with the CLI2 tool (for automated scenarios like CI).

**Comment by pgregory9** [comment]
Thank you. I got it now.
