### ISSUE TITLE
Occurrences highlight in the overview ruler breaks when extension is enabled.

### ISSUE THREAD

**Issue by serialprimate** [DavidAnson/vscode-markdownlint#352]
Thanks for a great extension.

When markdownlint is enabled using default options, the built-in occurrences highlight function does not show occurrences in the overview bar for the current word under cursor. It does show them in the editor.

Also the built-in selection highlight function does not show selection occurrences in the overview bar for the selected word.

Version information:
Last released
2024-09-12, 13:59:56
Last updated
2024-09-29, 08:30:47

When markdownlint is disabled and vscode is reloaded the overview bar shows the occurrences.

Snapshot:
![image](https://github.com/user-attachments/assets/7ab8c4f8-1be3-4449-baae-b1bd4ebeef7d)

**Comment by DavidAnson** [comment]
I can have a look, but all the rendering behavior you describe is implemented by VS Code, so any issues are likely to be theirs. Extensions just report on issues via metadata and VS Code handles the UI presentation.

**Comment by DavidAnson** [comment]
I tried this via VS Code on the web: https://github.dev/DavidAnson/vscode-markdownlint

It works fine there whether or not violations are present. Below is an example. I suspect something about your VS Code configuration or installed extensions is causing the behavior you observe.

![example](https://github.com/user-attachments/assets/0bdf4b29-4f5b-41c9-a63e-edb2f890ee6c)

**Comment by serialprimate** [comment]
Hi @DavidAnson thanks for checking and you are right.

I was able to replicate the bug using your link when I added the following settings and another random markdown extension (markdownlint not added -- markdownlint was the only extension I use for markdown):
{
    "markdown.occurrencesHighlight.enabled": true,
}

It *appears* that as soon as any (?) markdown extension is enabled that this bug is evident.

**Comment by serialprimate** [comment]
After some feedback that prompted more testing, this bug looks to be not specific to markdownlint -- just markdown mode maybe.
