### ISSUE TITLE
.htaccess file being linted as markdown

### ISSUE THREAD

**Issue by goldingdamien** [DavidAnson/vscode-markdownlint#356]
Why is this happening?
How to prevent this?

Regards.

**Comment by DavidAnson** [comment]
Seems like a duplicate of: https://github.com/DavidAnson/vscode-markdownlint/issues/257

Links to configuration docs: https://github.com/DavidAnson/vscode-markdownlint/issues/98#issuecomment-570301379

**Comment by goldingdamien** [comment]
@DavidAnson Thank you, you are correct.
I installed https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-apache
and then did the following to get it to change format: Set Language Mode => Auto Detect
