### ISSUE TITLE
MD026 - trailing punctuation in header

### ISSUE THREAD

**Issue by Serhioromano** [DavidAnson/vscode-markdownlint#36]
I have headers with question mark at the end. It is sort of FAQ. I think it should be allowed to use `?` at the end of a header.

**Comment by DavidAnson** [comment]
You can customize the list of punctuation.

That is discussed here: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md026

And here is an example: https://github.com/DavidAnson/markdownlint/blob/master/test/header_trailing_punctuation_customized.json

**Comment by Serhioromano** [comment]
OK, Iэму seen that, but I could not find in what JSON file I have to put it. Should it be special file or in package.json or in VS Code settings json.

**Comment by DavidAnson** [comment]
This explains the different options:
https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#configure
