### ISSUE TITLE
Ignore VS Code default exclusions

### ISSUE THREAD

**Issue by TomasHubelbauer** [DavidAnson/vscode-markdownlint#38]
Hey, I notice that `createFileSystemWatcher` does not allow for inserting the list of default VS Code exclusions unlike for example [`findFiles`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#workspace.findFiles) with its `exclude` argument you can set to `undefined` to make it use the default built-in excludes. That means currently this extension reports errors from even `node_modules` and such and in my case that blows some of my projects up to thousands of errors. You might want to consider trying to somehow extract this exclusion list from VS Code and adjusting your glob (either statically or even better dynamically based on the exclusion list) to ignore these.

**Comment by TomasHubelbauer** [comment]
Maybe this is a problem with my Code then, I'll try to repro without extensions and put up a repro if I can get it.

**Comment by TomasHubelbauer** [comment]
This is _probably_ an issue with my setup _somehow_. I was not at all able to discern how, but it must be. I will continue trying to figure this out in the linked issue and am closing this one as it doesn't appear to be a problem with this (awesome, BTW) extension, but general glob filtering in my VS Code installation.

**Comment by DavidAnson** [comment]
Ok, thanks, good luck! :)

**Comment by borekb** [comment]
Am I possibly hitting the same issue as @TomasHubelbauer? I get thousands of errors if I open any Markdown file and press `Ctrl+T` to use the new [Markdown workspace symbol search](https://code.visualstudio.com/updates/v1_23#_markdown-workspace-symbol-search).

The Ctrl+T operation takes relatively long and I get about 9 thousand markdownlint errors in our monorepo, with many hits from `node_modules` and `vendor` (PHP thing).

**Comment by TomasHubelbauer** [comment]
I ended up having to do this hack:

https://github.com/TomasHubelbauer/vscode-markdown-link-suggestions/blob/master/src/extension.ts#L49

The default exclusions just didn't work for me and I wasn't sure it was my setup or a general problem but to have a little more control (and be in line with what I consider to be a more reasonable behavior, I just copy paste the above code to all my extensions.

https://github.com/Microsoft/vscode/issues/48674

This is still open as a feature request from me to make the `findFiles` API better, but I don't think there is intention to change the default behavior to pick up the `node_modules`-containing section of default excludes in `findFiles`. :-/

**Comment by borekb** [comment]
Thanks, Tomas. And do you understand why doing Ctrl+T would kick in markdownlint on all MD files in my workspace?

**Comment by TomasHubelbauer** [comment]
I think Ctrl+T is dogfed by the extension APIs which don't seem to use the right excludes (I may be totally wrong on this) and as a result you are seeing this behavor. I think you can "fix it" by adding `node_modules` to `files.exclude` (that's what `findFiles` uses - if I am right and Ctrl+T uses `findFiles`).

**Comment by borekb** [comment]
Thanks. I still don't understand why Ctrl+T would start markdownlint-ing anything to be honest, seems like two unrelated things to me.

**Comment by borekb** [comment]
BTW, in my case, `files.exclude` only contains things I absolutely don't want to see like `.git` and `.DS_Store` while `search.exclude` hides things like `node_modules` and `vendor`. In this setup, VSCode symbol navigation actually looks into `node_modules` and `vendor` which I prefer as I'm able to navigate to library symbols.

It is less clear to me whether VSCode should treat various MD headings in `node_modules` as navigable symbols but OK, that's how it behaves. _But_ for markdownlint to also lint those file, that is not desirable I would argue.

So maybe there might be two small issues here?

1. Linting should not be started by Ctrl+T.
2. `search.exclude` should be markdownlint's default filter, not an empty array.

**Comment by DavidAnson** [comment]
Note: I typed that glob on my phone, it may need tweaking to work for real.

**Comment by borekb** [comment]
I'm trying to reproduce on a small example repo and everything behaves correctly. I also have two larger repos where I can reproduce.. As usual :) Thanks @DavidAnson for trying to help!

**Comment by borekb** [comment]
Oh, I was wrong! I thought that most of the invalid hits are in `node_modules` and `vendor` folders but it's actually just `vendor`.

How does the default ignore behavior look like, please? What would make Markdown files in `node_modules` ignored while those in `vendor` not?

Here are our workspace settings:

```
"files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/.DS_Store": true
},
"search.exclude": {
    "**/node_modules": true,
    "**/vendor": true,
    "**/dist": true,
    "**/*.js": {"when": "$(basename).ts"},
    "**/*?.js": {"when": "$(basename).tsx"},
    "**/*.js.map": {"when": "$(basename)"}
}
```

Is .gitignore considered somehow? Our root .gitignore is just:

```
node_modules
.idea
yarn-error.log
```

There is just `node_modules` here. The `vendor` folder is ignored in a nested .gitignore file, `subproject/.gitignore`:

```
/vendor
/node_modules

/dist
/build
```

Does this possibly matter?

**Comment by DavidAnson** [comment]
Could you maybe create a small repo that shows the problem and I will clone it and have a look? There is still a lot going on above that I’d like to filter out. :)

**Comment by borekb** [comment]
v1 published: https://github.com/borekb/markdownlint-vendor-demo

**Comment by borekb** [comment]
My plan:

- v2: adding `package.json` to see if it can be reproduced with `node_modules` as well.
- v3: playing with settings.

Good plan or a waste of time? :)

**Comment by borekb** [comment]
v2 is up: https://github.com/borekb/markdownlint-vendor-demo

**Comment by DavidAnson** [comment]
I won’t have time to look till this evening. Anything you do between now and then is pure goodness in my book. :)

**Comment by DavidAnson** [comment]
Feature request: Can you please put some files in place so I don’t need to run Composer or Docker?

**Comment by borekb** [comment]
> Feature request: Can you please put some files in place so I don’t need to run Composer or Docker?

I could but then it eliminates the option that it could be caused by `.gitignore` :) But it probably isn't so I'll commit all the files.

**Comment by DavidAnson** [comment]
Just a couple files. Keep it simple, please!

**Comment by borekb** [comment]
Oh, it becomes clearer when removing `.gitignore`:

![image](https://user-images.githubusercontent.com/101152/40687410-d20a8ace-639a-11e8-9fe5-4e250786a199.png)

node_modules is still grayed out. In default settings:

![image](https://user-images.githubusercontent.com/101152/40687453-f71e5a34-639a-11e8-820d-63e9394aab00.png)

**Comment by borekb** [comment]
And this is where I stop understanding it. I have copied both settings to my user settings and added vendor:

![image](https://user-images.githubusercontent.com/101152/40687642-9ffea23a-639b-11e8-9130-4a9a81bb8d2c.png)

but I'm still getting hits from `vendors`, and `vendors` only:

![image](https://user-images.githubusercontent.com/101152/40687656-ac825a10-639b-11e8-8845-f41d2dc752ca.png)

and it is checked by linter while `node_modules` aren't:

![image](https://user-images.githubusercontent.com/101152/40687689-c146c292-639b-11e8-8c00-6af53142dafc.png)

Ok, I'm giving up for tonight :) Hopefully you'll be able to make better sense of this than me.

**Comment by DavidAnson** [comment]
Looking at VS Code on my machine, I see the following behavior (always re-open the folder when testing).

Prevents linting *.md from vendor directory, but hides directory in explorer:

    "files.exclude": {
        "**/vendor": true
    },

Does not exclude *.md from vendor directory:

    "search.exclude": {
        "**/vendor": true
    }

Also does not exclude:

    "files.watcherExclude": {
        "**/vendor/*/**": true
    },

Which brings me back to suggesting `markdownlint.ignore`.

Prevents linting *.md from vendor directory, no effect on explorer, no effect on `Ctrl+T`:

    "markdownlint.ignore": [
        "vendor/**"
    ]

Code-wise, I confirm that VS Code's handling of `Ctrl+T` is to invoke `vscode.workspace.onDidOpenTextDocument` for every Markdown document it scans.
There is no matching call to `vscode.workspace.onDidCloseTextDocument`. Either or both may be a bug.

I can't yet see a way to tell the `Ctrl+T` scenario apart from the normal document open scenario from the extension's code.

`markdownlint.ignore` seems to be the ideal solution for now.

**Comment by borekb** [comment]
Thanks, great research! Do you have any idea why Markdown files in `vendor` would be processed while those in `node_modules` not? I have a clean installation of VSCode Insiders with no custom settings so VSCode shouldn't have any special knowledge about `node_modules`, except for `search.exclude` and `files.watcherExclude` supposedly don't influence anything linter-related.

**Comment by borekb** [comment]
@TomasHubelbauer Is [your extension](https://marketplace.visualstudio.com/items?itemName=TomasHubelbauer.vscode-markdown-link-suggestions) impacted similarly? I tried to install it and it reports missing links in various unopened Markdown files.

**Comment by DavidAnson** [comment]
FYI, I think VS Code does have special knowledge and handling. I spent a couple of minutes yesterday and found these things that may be relevant:

- https://github.com/Microsoft/vscode/commit/b845ce918f2689344795e845ae6ef691916c3079
- https://github.com/Microsoft/vscode/commit/a7b1e6ccd2973d8d46d8a97777c720a6958aba64
- https://github.com/Microsoft/vscode/issues/23954

**Comment by DavidAnson** [comment]
More FYI, @chrmarti kindly opened an issue for VS Code to look into this: https://github.com/Microsoft/vscode/issues/50874

What we’re seeing may not be entirely expected.
