### ISSUE TITLE
Linting inside $$ (add support for non-CommonMark math blocks)

### ISSUE THREAD

**Issue by cossio** [DavidAnson/vscode-markdownlint#40]
Linting has problems inside equation blocks. For example:

![image](https://user-images.githubusercontent.com/10637482/39828518-5521e960-5389-11e8-892f-39e9627c83f6.png)

Here the linter thinks that the `+` signs are a list and gives the following warning:

     [markdownlint] MD032/blanks-around-lists: Lists should be surrounded by blank lines

Maybe the linter should be disabled entirely within math (inline $, and block $$).

**Comment by DavidAnson** [comment]
Math blocks are not part of the CommonMark specification: https://spec.commonmark.org/0.28/

I found a spec for them in kramdown: https://kramdown.gettalong.org/syntax.html#math-blocks

I will consider adding support for math blocks. Thanks!

**Comment by gandalfsaxe** [comment]
Would love to see it disabled inside math blocks as well 🙂

**Comment by DavidAnson** [comment]
I plan to look at this, but it will be a couple of weeks before I get to it.
