### ISSUE TITLE
Markdown Lint stopped working

### ISSUE THREAD

**Issue by rich-fts** [DavidAnson/vscode-markdownlint#41]
I have Markdownlint installed as part of the Markdown all in one package.  I am not getting any lint errors any more (as of about a week ago).  Did something change within the package?

**Comment by DavidAnson** [comment]
Things to try:
- Go to VS Code extension tab and confirm markdownlint is installed and report the version
- Open a MD file, open the VS Code Output window, find markdownlint in the list, and report what it says about trying to lint that file
- Report if this problem  is isolated to a particular MD file, or applies to all of them
- If you or a friend have a different machine, say if the problem is also present there
- Try uninstalling and reinstalling markdownlint?

Thanks!

**Comment by rich-fts** [comment]
Thank you – Markdownlint is indeed running.  What the issue is, is that it is not detecting trailing spaces when it used to.  I looked at the workspace setup and the MD013 rule is set to false, but otherwise the rules look OK.

Just in case – here are all the settings:

// markdownlint config object
  "markdownlint.config": {
    "MD013": false
  },

  // Array of paths for custom rules to include when linting
  "markdownlint.customRules": [],

  // Array of file names and glob expressions to ignore when linting
  "markdownlint.ignore": [],

  // Run the linter on save (onSave) or on type (onType)
  "markdownlint.run": "onType"



Rich Taylor
Co-Founder & Senior Vice President
[cid:image002.png@01D3FE7F.9E8A45C0]<http://www.fintechstudios.com/>

**Comment by DavidAnson** [comment]
Also, if it’s just trailing space behavior that is different, is there a chance the change for this issue is relevant? https://github.com/DavidAnson/markdownlint/issues/114

**Comment by rich-fts** [comment]
You nailed it.  Thank you.  Unfortunately, the linting in the GitHub library still flags two spaces as an error, but I can work with this.

Rich Taylor
Co-Founder & Senior Vice President
[cid:image002.png@01D3FF06.EF7AB780]<http://www.fintechstudios.com/>

**Comment by DavidAnson** [comment]
OK, great, thank you for letting me know! I'm sorry for the trouble here, I did debate making that change to the rule. But ultimately I felt like it was improper to report a violation on valid text.

**Comment by DavidAnson** [comment]
I should point out that all I did with that change was to adjust the default value of the `br_spaces` parameter for `MD009`. You should be able to customize that rule (see the README) to set that parameter back to 0 and restore the previous behavior.

**Comment by rich-fts** [comment]
Ok – Thank you.  Funny, but I was using the double space to force line breaks, but stopped because I was getting the lint error.  😊

I agree with your change.  I just need to synch it up with our company lint process on GitHub.

Rich Taylor
Co-Founder & Senior Vice President
[cid:image002.png@01D3FF20.22D92990]<http://www.fintechstudios.com/>
