### ISSUE TITLE
My vscode user settings don't work. Am i doing something wrong?

### ISSUE THREAD

**Issue by JoeCodeswell** [DavidAnson/vscode-markdownlint#45]
Here's my vscode user settings for markdownlint:

    "markdownlint.ignore": [
    "no-inline-htm",
    "no-trailing-punctuation"
    ]

I have closed & reopened vscode.
I did a search of my entire C: drive. I can't find any file named ".markdownlint.config".
I m still getting problems: 

    MD026/no-trailing-punctuation: Trailing punctuation in heading [Punctuation: '?']
    MD033/no-inline-html: Inline HTML [Element: br]

Thanks for the good extension.

Love and peace,
Joe

**Comment by DavidAnson** [comment]
`ignore` is for files, not rules. It is documented here: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintignore

To configure or disable rules, use `config`. Documentation and examples here: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

You can set both rules to `false` to disable them. VS Code will help syntax check your edits. Make sure the rule names are correct (add the missing 'l').

**Comment by JoeCodeswell** [comment]
Thanks for the clarification, David.
Love and peace,
Joe
