### ISSUE TITLE
How to use inline config comments into lists

### ISSUE THREAD

**Issue by oshliaer** [DavidAnson/vscode-markdownlint#49]
I need disable a line in my list

```markdown
- [google-docs](https://github.com/fastfedora/google-docs) Libraries and functions used within Google Docs
- <!-- markdownlint-disable MD034 -->[youtube/api-samples/apps-script](https://github.com/youtube/api-samples/tree/master/apps-script/snippets) The youtube-data-api.gs file in this directory contains code snippets that are generated by the Data API code snippet tool at: https://developers.google.com/youtube/v3/code_samples/code_snippets<!-- markdownlint-enable MD034 -->
- [google/google-apps-script-samples](https://github.com/google/google-apps-script-samples) Various sample code and projects for the Google Apps Script platform
```

But the code above is resolved.

![mdlint01](https://user-images.githubusercontent.com/5027939/45862875-5f768f80-bd7c-11e8-89b2-acf7f97f6a23.png)
![mdlint02](https://user-images.githubusercontent.com/5027939/45862878-643b4380-bd7c-11e8-9764-663e650bc127.png)

Any ideas?

**Comment by DavidAnson** [comment]
Could you please try each of:

- Adding a space around the comments so the </> characters are not touching the link and text?
- Moving the comments to above/below the entire list?
- Removing the comments and putting the link in </> so it isn’t a bare link?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
