### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pauby** [DavidAnson/vscode-markdownlint#5]
When I try to install in VS Code I get:

```
Error: write EPROTO 0:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:c:\jenkins\workspace\
electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:769:

at exports._errnoException (util.js:1026:11)
at WriteWrap.afterWrite (net.js:795:14)
```
There are no dependencies listed for the extension - are there any?

**Comment by DavidAnson** [comment]
This appears to be an issue with VS Code itself. The corresponding issue has more details and a possible workaround: https://github.com/Microsoft/vscode/issues/14672
