### ISSUE TITLE
Reorder Show Fixes (Ctrl+.) popup to highlight "Click to fix violation..." first

### ISSUE THREAD

**Issue by gojanpaolo** [DavidAnson/vscode-markdownlint#52]
Hello,

Is it possible to reorder the popup so the fix is highlighted first?
This would allow us to just `Ctrl + .` then `Enter` to fix the violation.

Current behavior:
![image](https://user-images.githubusercontent.com/16026608/49308975-6669fe80-f49f-11e8-80e0-a3084abdc7ea.png)

Thank you! :)

**Comment by DavidAnson** [comment]
Sure, thanks!
