### ISSUE TITLE
vsix release

### ISSUE THREAD

**Issue by timoline** [DavidAnson/vscode-markdownlint#57]
Is it possible for you to also release a vsix version?

**Comment by timoline** [comment]
Most extensions also provide their extension in a VSIX format, (Packaged Extension)
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by DavidAnson** [comment]
Interesting, I didn't know about that!

It sounds like it's intended for limited distribution/test environments: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#sharing-privately-with-others

What's the scenario where manually downloading an extension from the web is preferable to installing from the VS Code Marketplace?

**Comment by timoline** [comment]
Thats an easy one.
Our (otap) environment doesnt have internet access. so installing from the marketplace is a nogo.

**Comment by DavidAnson** [comment]
I’ll look at doing this next time I publish an update - should be soon.

**Comment by DavidAnson** [comment]
It turns out, you can download the VSIX of *any* extension directly from the Marketplace - here’s how: https://code.visualstudio.com/docs/editor/extension-gallery#_can-i-download-an-extension-directly-from-the-marketplace

**Comment by timoline** [comment]
ok I didn't know that, cool.
Thanks
