### ISSUE TITLE
Feedback on VS Code proposed Code Action Auto Fix APIs

### ISSUE THREAD

**Issue by mjbvz** [DavidAnson/vscode-markdownlint#59]
Hi, I'm on the VS Code team. We are exploring extending VS Code's code actions to support automatic fixes and auto fix on save. You can find the two current proposal [here](https://github.com/Microsoft/vscode/issues/62110#issuecomment-454182230)

Your extension is a large user of code actions so we'd appreciate your feedback on these API proposals. Here are example use cases for these two areas:

- For auto fix: I write some markdown that causes a linter failure. This is shown as a red squiggly in the editor. I F8 to the error and then use a single keyboard shortcut to auto fix the failure This fix has been marked as the preferred auto fix by your extension. Other alternative fixes could be provided in the existing lightbulb menu

- For fix all: I open an old md document that has a bunch of linter errors. Thankfully, I've enabled `"editor.codeActionsOnSave": { "source.autoFix": true }` and your extension provides an `autofix` code action. This autofix action looks through the entire document and fixes all trivial errors in a single pass. So all I need to do is save the document and many of the simple errors are addressed

[This guide](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) covers how to use VS Code's proposed APIs. Please let me know if you have any questions about these proposals, feedback on the API, or ideas for other auto-fix scenarios that you would like to see supported in VS Code

**Comment by DavidAnson** [comment]
Provided feedback in the proposal.
