### ISSUE TITLE
.markdownlint.yml

### ISSUE THREAD

**Issue by Coalpha** [DavidAnson/vscode-markdownlint#60]
This extension recognizes `.markdownlint.yaml` but it doesn't recognize `.markdownlint.yml`. I know it's a nitpick but I'd still like to use the `.yml` file extension since the rest of my YAML files use it too.

**Comment by syntaqx** [comment]
@DavidAnson Any traction on this so far? Or is this something you're interested in seeing a PR for? Would love to have this functionality for both markdownlint and the vscode extension.

Which project is responsible for determining what files to look for?

**Comment by DavidAnson** [comment]
I expect to get to this in the next couple of days and release a new version of the extension a couple of days after that. Thanks for your patience!

**Comment by Coalpha** [comment]
Thanks for the prompt response :)
This extension is really nice.
