### ISSUE TITLE
Configuration file other than in workspace folder

### ISSUE THREAD

**Issue by jorisvanderpol** [DavidAnson/vscode-markdownlint#62]
Hi,

I'm working on a multidisciplinary project and for each discipline we have a specific workspace tailored. At the moment we have the configuration either in a json file in a certain directory or in the workspace settings. Since we want to avoid duplication and want to unify, it is possible to set a configuration file in the workspace settings. This way the configuration is in one location and the json files do not clutter the workspace.

**Comment by DavidAnson** [comment]
I'm not sure I understand the scenario, but what I think you can do is create a `markdownlint.json` file in the root of each workspace (where it will be automatically used) and use the `extends` setting inside to point all of those to a single `markdownlint.json` file where you put the settings for all projects.

https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

If this doesn't make sense, please show me an example of your file structure.

**Comment by jorisvanderpol** [comment]
That works indeed! I read the documentation too fast.

Thanks!

**Comment by DavidAnson** [comment]
Yay!
