### ISSUE TITLE
.markdownlintrc support?

### ISSUE THREAD

**Issue by morten-nielsen** [DavidAnson/vscode-markdownlint#64]
How is it possible that markdownlint in vscode, considers the same rule exceptions that I apply in my CI/CD defined in .markdownlintrc?

**Comment by DavidAnson** [comment]
The VS Code extension and the CLI both support `.markdownlint.json` (or `.yaml`) configuration. The CLI also (and only) supports `.markdownlintrc` files because of the `rc` library it uses. If you want something that is supported by both tools, please use the JSON or YAML formats.

**Comment by morten-nielsen** [comment]
Thanks this works, although the cli must be run in the directory of `.markdownlin.json` or alt. use the `--config` to reference the file. The cli will not look in current or all upper folders for the json file, however that seems to be the behaviour in the vscode extension - which is good.
