### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pcfe** [DavidAnson/vscode-markdownlint#65]
- Issue Type: `Performance`
- Extension Name: `vscode-markdownlint`
- Extension Version: `0.24.0`
- OS Version: `Linux x64 4.20.10-200.fc29.x86_64`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/pcfe/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt` :warning:

[DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt](https://github.com/DavidAnson/vscode-markdownlint/files/2896591/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by pcfe** [comment]
both swyphcosmo/vscode-spellchecker#57 and DavidAnson/vscode-markdownlint#65 occurred during the same session. 10 other extensions remained responsive during that session.

**Comment by DavidAnson** [comment]
The three commits above reduce the activation time of the `vscode-markdownlint` extension by roughly 75% in my test scenario. That looks to be the scenario captured in your CPU profile, so I think things should be better for you when I release the next version. Thanks for the detailed report!
