### ISSUE TITLE
Unable to create preformatted text inside ordered list

### ISSUE THREAD

**Issue by felipe1982** [DavidAnson/vscode-markdownlint#66]
I am not able to successfully create preformatted text (ie shell commands) inside of ordered list and continue the numbering while fulfilling the suggestions of this extension. I apologise in advance for using images, but this best describes what I am trying to express.

----

Below satisfies the extension, but does not produce a successful outcome:

![2019-03-14 15_30_53-README md - workspace-youi (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/275621/54333603-df681d00-466e-11e9-8224-2fbd12ad1252.jpg)

----

Below does not satisfy the extension, but produces the desired outcome.

![2019-03-14 15_30_37-README md - workspace-youi (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/275621/54333605-e131e080-466e-11e9-8075-14828853c506.jpg)

**Comment by DavidAnson** [comment]
This seems to work for me (three spaces indent for the fence to match the list marker size):

````md
# Heading

1. One
1. Two
1. Three

   ```js
   const pi = 3.14
   ```

1. Four
````

**Comment by felipe1982** [comment]
Ah. The **3** spaces did it for me. Was using even-numbered indentation. Thanks.
