### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by koyo-jakanees** [DavidAnson/vscode-markdownlint#67]
- Issue Type: `Performance`
- Extension Name: `vscode-markdownlint`
- Extension Version: `0.25.0`
- OS Version: `Linux x64 4.14.105-1-MANJARO`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/jakanees/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DavidAnson** [comment]
Please attach the profile per the directions above.
