### ISSUE TITLE
formatOnSave, bullets, and MD030

### ISSUE THREAD

**Issue by wesbaker** [DavidAnson/vscode-markdownlint#69]
I have formatOnSave enabled and markdown lint installed. When I save a bullet point it's "fixed" to have additional spaces after the bullet.

```markdown
- bullet item
```

Is "fixed" to:

```markdown
-   bullet item
```

I can always disable formatOnSave for Markdown, but I was curious if anyone knew of another way to fix it.

**Comment by DavidAnson** [comment]
I think `formatOnSave` is coming from the Prettier extension you have installed? https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

So you could configure the formatting behavior differently in that extension or disable the rule in the `markdownlint` extension. Seem reasonable?

**Comment by DavidAnson** [comment]
Some more info here, by the way: https://github.com/DavidAnson/markdownlint/issues/137

See also the Prettier issue referenced toward the end.

**Comment by wesbaker** [comment]
Yeah, looks like Prettier added Markdown support at some point. Adding this to the config fixed it for me:

```json
"prettier.disableLanguages": [
  "markdown"
]
```

Thanks for your help!
