### ISSUE TITLE
MD013 globally enabled & broken rule processing

### ISSUE THREAD

**Issue by jboeshart** [DavidAnson/vscode-markdownlint#70]
Rule MD013 appears to no longer be disabled globally, and I'm wondering if it's related to changes in the following commit. Possibly related, even though I have the rule set to false in my settings.json, it's still flagging it. To test if it's just an issue with that rule or something else, I added MD036 to my settings.json and it didn't disable that rule either, so I'm wondering if rule processing is broken in some way.

https://github.com/DavidAnson/markdownlint/commit/d7c0d195d7cef4747d66aaa3111a6a176a2c3d4a#diff-6ec48d1fef72234d36767f4aa664ec16

**Comment by DavidAnson** [comment]
I confirm that `MD013` is still disabled by default and `MD036` can be disabled in user settings. Here's the VS Code Output window for category `markdownlint` for opening a folder with just a `README.md`:

```
[1:41:51 PM] INFO: Loading user/workspace configuration for 'c:\T\empty\README.md' (no configuration file in workspace folder).
[1:42:11 PM] INFO: Linting for 'c:\T\empty\README.md' will be run 'onType'.
```

What I'm guessing is going on in your case is that a project-local `.markdownlint.json` file is overriding your user settings. Here's how that looks in the Output window:

```
[1:47:42 PM] INFO: Loading custom configuration from 'c:\T\empty\.markdownlint.json', overrides user/workspace/custom configuration for directory and its children.
```

And here's the relevant documentation: https://github.com/DavidAnson/vscode-markdownlint#configure

If that doesn't help, please point me to a sample repository or include steps to demonstrate the problem along with the content of your VS Code Output window for category `markdownlint`.

Thanks!

**Comment by jboeshart** [comment]
Does the `.markdown.json` fully override any values in user settings? The repo/branch I'm working in does have that file present, but it does not have MD013 in the list. Would that override the default disable and my `settings.json` entry as well? That seems to be the case, as it only disables that rule once I add that as disabled in `.markdown.json`.

**Comment by DavidAnson** [comment]
Yes, if a project-local configuration file is present then it is assumed to specify the complete rule configuration for that project.

This is so individuals can have whatever user settings they prefer by default for their own environment, without those settings “leaking“ in when they work on a project whose maintainers have a different set of preferences.

**Comment by jboeshart** [comment]
Makes sense. That functionality isn't entirely clear in the readme. Any objections if I add in a note to clarify this for future reference? 

In the hierachy below, does each one fully override the previous?

* `.markdownlint.{json,yaml,yml}` file in the same directory
* `.markdownlint.{json,yaml,yml}` file in a parent directory
* `.markdownlint.{json,yaml,yml}` file in the root of the project
* Visual Studio Code user/workspace settings
* Default configuration (see above)

Thanks for the help and clarfication here @DavidAnson!

**Comment by DavidAnson** [comment]
No objections! And yes, first match wins.

**Comment by DavidAnson** [comment]
Clarified this here: https://github.com/DavidAnson/vscode-markdownlint/commit/150911819a2157814ddec3cb926c5eb74eb631d4

**Comment by jboeshart** [comment]
Thanks for adding that clarification @DavidAnson! I (obviously) hadn't gotten around to adding that in.
