### ISSUE TITLE
Idea: Show source of markdownlint.config rules

### ISSUE THREAD

**Issue by serotta58** [DavidAnson/vscode-markdownlint#71]
In order to avoid confusion when one config file overrules another, or the VSCode user settings, it would be handy if we could see which set of rules is being used.  Perhaps an indication could be added to the popup error message.  For example, instead of ending with the rule alone:
`... markdownlint(MD033)`
it could say
`... markdownlint(MD033) from ./.markdownlint.json`
or something like that.

**Comment by DavidAnson** [comment]
FYI, I put this in the Problems list first, but it was repetitive and made things harder to understand. So I put it in the context menu for a violation where it seems to fit well with the other options.
