### ISSUE TITLE
Auto table formatting

### ISSUE THREAD

**Issue by Ilias48rus** [DavidAnson/vscode-markdownlint#74]
Can you please add an Auto markdown table formatting functionality (so it would visually format such table on edit, for example 1-ce in a 3 sec or so or on a cell switch, like the Atom's [markdown-table-editor package](https://atom.io/packages/markdown-table-editor) have).

**Comment by DavidAnson** [comment]
That sounds like something the Prettier extension may already do: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

This extension is more about validating documents for consistency vs. applying styles dynamically.

**Comment by Ilias48rus** [comment]
@DavidAnson it obviously don't, like a thing that have no relation to the case at all

**Comment by DavidAnson** [comment]
Here is a link with some examples of how Prettier formats Markdown, including tables: https://prettier.io/blog/2017/11/07/1.8.0.html

**Comment by Ilias48rus** [comment]
@DavidAnson , though it may be true, after some looking in, i'll rather additionally use an Atom with the package than figuring out this whole new command-line utility just for the 1, so basic function, even not saying about installing anything more than the editor package, that seem to be needed for the Prettier.

**Comment by Ilias48rus** [comment]
@DavidAnson , or, more correctly saying, the summary is that it can't be named a normal/sufficient solution for the VSC case.

**Comment by Ilias48rus** [comment]
@DavidAnson , Why?

**Comment by DavidAnson** [comment]
I explained why I think this is a job for Prettier above - and you said you would rather use a different tool.

**Comment by Ilias48rus** [comment]
Rather than the Prettier, because IT is not enough efficient solution, unlike the feature in this extension. And i tried the Prettier and it didn't work that way.

**Comment by Spenhouet** [comment]
@DavidAnson markdownlint has multiple options to configure how tables are to be formatted: https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md060.md

But prettier only supports the "aligned" option and has no configuration for markdown what so ever (since 7 years).

I propose to reconsider this feature request or should I open a fresh one?

**Comment by DavidAnson** [comment]
As you point out, some rules have been added to markdownlint over the past seven years to check table formatting. There are also already some issues asking for those to be more able to fix violations. What is it that this issue represents that you think is unique to explain reopening it?

**Comment by Spenhouet** [comment]
What I'm missing is the Autofix for the MD060 rule. That would be really handy and it seems all existing markdown formatters in VS code can not do it.

**Comment by DavidAnson** [comment]
Existing issue: https://github.com/DavidAnson/markdownlint/issues/1980

**Comment by Spenhouet** [comment]
Missed that Feature request. Thanks.
