### ISSUE TITLE
Quick fixes for more complicated rule scenarios

### ISSUE THREAD

**Issue by Hipska** [DavidAnson/vscode-markdownlint#78]
I just discovered that some rules have quick fixes, it looks to me that this can be perfectly done as wel for:

* [MD031 - Fenced code blocks should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md031)
* [MD032 - Lists should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md032)

Although it can be 2 options for list items (add a newline or indent line).

**Comment by DavidAnson** [comment]
I've looked at a couple of approaches here - to do this well and more generally, information about the edit should really come from the underlying `markdownlint` library. That's already on the TODO list there, so I'll revisit this if/when that becomes available.

**Comment by Hipska** [comment]
Sounds good. Can you link the issue, so we can follow?

**Comment by DavidAnson** [comment]
Yep: https://github.com/DavidAnson/markdownlint/issues/80

**Comment by DavidAnson** [comment]
FYI, MD031/MD032 will have quick fixes in the next release: https://github.com/DavidAnson/markdownlint/commit/a062e7c6bd929c5447efabdd447ccbedd04d87a8

**Comment by jsuddsjr** [comment]
Add this one to your list of enhanced fixes:

* [MD012 - Multiple consecutive blank lines](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md012)

**Comment by DavidAnson** [comment]
I got you, fam: https://github.com/DavidAnson/markdownlint/commit/2cd27c58f2df6f215aa935ba33261d288cb950cb

**Comment by Hipska** [comment]
You also have anything for this one?
* [MD029 - Ordered list item prefix](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md029)

**Comment by DavidAnson** [comment]
No. Because the default mode is to allow either 1/1/1 or 1/2/3, it won’t be completely clear how to fix a violation in some cases where a file may have both. I could make this smarter eventually, but for now I have added something like eight new rule fixes that are pretty unambiguous. I should be able to publish an update soon.
