### ISSUE TITLE
Workspace config not working

### ISSUE THREAD

**Issue by unional** [DavidAnson/vscode-markdownlint#8]
```js
// workspace settings
{
  "markdownlint.config": {
    "MD028": false
  }
}
```

```markdown
# Test

> quote 1

> quote 2
```

It still shows warning in the "Problem" Panel:

```sh
severity: 'Warning'
message: 'MD028/no-blanks-blockquote: Blank line inside blockquote'
at: '4,1'
source: ''
```

**Comment by DavidAnson** [comment]
This scenario works fine for me. Can you please confirm that you have saved the `settings.json` file after making the workspace configuration change? That's easy to forget and changes don't take effect until the file is saved.

**Comment by unional** [comment]
Yes, I do have it saved and just in case I have close and re-open VSCode.

I also put the "test.md" under the root of the project.
And the warning still shows up.

**Comment by DavidAnson** [comment]
Does it work if you disable with `.markdownlint.config` instead?

What version of Code?

What version of the markdownlint extension?

Is it possible you have a setting for your project that is overriding the workspace setting?

**Comment by unional** [comment]
I figured out what's the issue.

I have `.vscode/settings.json` AND `/.markdownlint.json`. They are not merged and the `.markdownlint.json` overrides whatever in the `.vscode/settings.json`

**Comment by DavidAnson** [comment]
Yes, that is documented here: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#configure

The idea is to let projects override arbitrary user settings.

I will look into showing a notification when this happens to make it more clear. 

Thank you!

**Comment by unional** [comment]
Thanks to making the extension! 🌷
