### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by CheolHyeonParkKurly** [DavidAnson/vscode-markdownlint#83]
- Issue Type: `Performance`
- Extension Name: `vscode-markdownlint`
- Extension Version: `0.29.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/tf-mac-051/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DavidAnson** [comment]
Please attach the file specified above.

**Comment by rjj-work** [comment]
[DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt](https://github.com/DavidAnson/vscode-markdownlint/files/3452579/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt)
