### ISSUE TITLE
Can'd user snippet in markdown file

### ISSUE THREAD

**Issue by bonaluo** [DavidAnson/vscode-markdownlint#87]
I create a snippet file named markdown.json and define a snippet in it,but i can't use it in .md files.

**Comment by DavidAnson** [comment]
A file named `.markdownlint.json` with valid rule configuration JSON in it will be used by the VS Code markdownlint extension to customize the linting rules for Markdown files in that directory.

Custom snippets are not supported and neither is a file named `markdown.json`.

Here’s the relevant part of the README: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

**Comment by DavidAnson** [comment]
Closing per answer above.
