### ISSUE TITLE
Hope for support of MathJax

### ISSUE THREAD

**Issue by lyh543** [DavidAnson/vscode-markdownlint#90]

**Comment by DavidAnson** [comment]
There’s currently a KaTeX plugin to parse basic math unlined/blocks. What are you looking for with MathJax support? Parser support or specific rules?

**Comment by lyh543** [comment]
I use math equation in Tex, like:

```
$a+b$
$$a+b$$
\begin{equation}a+b\end{equation}
```

which is used in my [Hexo blog](https://lyh543.github.io/LaTeX/LaTeX%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/).

**Comment by DavidAnson** [comment]
What is the problem you are hitting? Your example does not seem to report any errors: https://dlaa.me/markdownlint/#%25m%23%20vscode-markdownlint%20issue%2090%0A%0AI%20use%20math%20equation%20in%20Tex%2C%20like%3A%0A%0A%20%20%20%20%24a%2Bb%24%0A%20%20%20%20%24%24a%2Bb%24%24%0A%20%20%20%20%5Cbegin%7Bequation%7Da%2Bb%5Cend%7Bequation%7D%0A%0Awhich%20is%20used%20in%20my%20Hexo%20blog.%0A

**Comment by lyh543** [comment]
> What is the problem you are hitting? Your example does not seem to report any errors: https://dlaa.me/markdownlint/#%25m%23%20vscode-markdownlint%20issue%2090%0A%0AI%20use%20math%20equation%20in%20Tex%2C%20like%3A%0A%0A%20%20%20%20%24a%2Bb%24%0A%20%20%20%20%24%24a%2Bb%24%24%0A%20%20%20%20%5Cbegin%7Bequation%7Da%2Bb%5Cend%7Bequation%7D%0A%0Awhich%20is%20used%20in%20my%20Hexo%20blog.%0A

```
\begin{equation}
\begin{split}
x&=a+b+c\\\\
&=d+e\\\\
&=f+g
\end{split}
\end{equation}
```

I want to render the equation like this:
![image](https://user-images.githubusercontent.com/15522311/64468991-bc21b480-d15d-11e9-86fd-a74a023b39c8.png)

I render it in my blog, using Mathjax.
The Original Github Flavored Markdown don't support equation, so I use Mathjax in my blog; Also, in Github.com, you can use [MathJax Plugin for Github](https://chrome.google.com/webstore/detail/ioemnmodlmafdkllaclgeombjnmnbima) to render in github.com

**Comment by DavidAnson** [comment]
This extension doesn’t render Markdown at all. It just looks for common mistakes in the way the text is written.  If you want VS Code to show the equation like above in the preview window, that is something for them to support or maybe you can find a different extension to render like that.

But rendering is not a scenario for this extension. Does that make sense?

**Comment by DavidAnson** [comment]
Something like this extension, maybe: https://marketplace.visualstudio.com/items?itemName=goessner.mdmath

**Comment by lyh543** [comment]
> Something like this extension, maybe: https://marketplace.visualstudio.com/items?itemName=goessner.mdmath

That make sense. Thank you so much.
