### ISSUE TITLE
Put vscode extension link on to GitHub repo

### ISSUE THREAD

**Issue by doggy8088** [DavidAnson/vscode-markdownlint#91]
I'd like to suggest the extension author put [extension link](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) on to GitHub.

![image](https://user-images.githubusercontent.com/88981/66186368-a51aa780-e6b4-11e9-8abb-f299524e1bdc.png)

**Comment by DavidAnson** [comment]
Great idea, I’ll do so this evening!

**Comment by DavidAnson** [comment]
Done from my phone!
