### ISSUE TITLE
[Feature] Generate .markdownlint.json file

### ISSUE THREAD

**Issue by doggy8088** [DavidAnson/vscode-markdownlint#92]
I'll be very good if this extension provide a command that can **Generate MarkdownLint Config** ( `.markdownlint.json` ).

Something like this:

![image](https://user-images.githubusercontent.com/88981/66249132-c7b6ca00-e761-11e9-8dc0-298827a051db.png)

**Comment by DavidAnson** [comment]
Already today, editing a `.markdownlint.json` configuration file will auto-complete all the rule names, parameters, and values.￼ So maybe ￼the only thing this new command would do is create the configuration file in the root of the project with the contents "{}"? Did you have something more in mind?￼

**Comment by doggy8088** [comment]
@DavidAnson Yes, that's what I mean. Just create that file. It maybe a blank file with `.markdownlint.json` filename. Or you can fill some default rules in that file.

**Comment by DavidAnson** [comment]
Notes to self:
- Requires [workspace.fs](https://code.visualstudio.com/updates/v1_37#_vscodeworkspacefs) introduced in VS Code 1.37.
- Current SAW version 1.35.1 is too early.

**Comment by doggy8088** [comment]
@DavidAnson What's `SAW` version?

**Comment by DavidAnson** [comment]
An internal environment that can’t be upgraded. I try to keep the required VS Code version usable there. It updates periodically and I check every now and then.

**Comment by AdrianBinDC** [comment]
Where should the `.markdownlint.json` be placed?

**Comment by doggy8088** [comment]
@AdrianBinDC It can be placed any folder and place on root folder of the current workspace by default.

**Comment by DavidAnson** [comment]
As a general command in the palette, I don’t think it wouldn’t know any better than to create the file in the root of the project. To create it in subdirectories would probably be most appropriate as a file tree handler that responded to right click on directories. I’m not sure offhand if that’s possible or how involved it would be to do.
