### ISSUE TITLE
Possible Bug: Extension Host crashing in Visual Studio Code 1.40.1

### ISSUE THREAD

**Issue by timosperisen** [DavidAnson/vscode-markdownlint#94]
Hi,

Thank you for making this extension!

I updated Visual Studio Code today and the extension host crashed. I tried disabling different extensions and when disabling vscode-markdownlint it did not crash anymore.

Extension Version: 0.32.0

Visual Studio Code About Info:
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

What kind of data could I provide you to help you analyzing this issue?

Thank you!

**Comment by DavidAnson** [comment]
This is the first such report I’ve heard. Are you saying VS Code crashes when and only when you have the vscode-markdownlint extension installed? How do you know the host is crashing? Is there any info about the crash in the output window? Does it depend on what file(s) are open in the workspace? Can you reproduce the problem on another machine? Could you try uninstalling both the extension and VS Code?

**Comment by timosperisen** [comment]
I will try it out on a different machine and report back with my findings.

**Comment by timosperisen** [comment]
Visual Studio Code itself did not crash but it displays a message in the lower right corner saying "Extension host terminated unexpectedly":
![grafik](https://user-images.githubusercontent.com/2643816/69358945-fe03c680-0c87-11ea-9033-eb2fb0b1926d.png)

Clicking the button "Restart Extension Host" repeats the behavior.
Clicking the button "Open Developer Tools" shows following messages:
![grafik](https://user-images.githubusercontent.com/2643816/69359093-428f6200-0c88-11ea-9a27-dee4ed5b054b.png)


On a different machine I first removed all extensions, then updated Visual Studio Code to the current version aswell:

Data from 2nd machine:
Extension Version: 0.32.0

Visual Studio Code About Info:
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763


On both machines this seems to happen when opening an .md file or when an .md file is still open from the last session. If I create a new file in Visual Studio Code and then save it as .md file it does not happen.

I will now try to Uninstall Visual Studio Code and reinstall it, then reinstall the extension.

**Comment by timosperisen** [comment]
With a fresh install of Visual Studio Code the behavior is the same. I also tried installing older versions of the extension. The same message appeared. 

Either I am missing something or The new version of Visual Studio Code does something that leads to this behavior.

**Comment by DavidAnson** [comment]
Thanks for the help and for trying all of that! I and many others are also on the new version and not seeing this problem, so I think there’s more going on here. I really appreciate that you tried older versions of the extension; that helps rule out a recent change on my side and does more to suggest something is going on in VS Code itself. I will send an email to someone I know internally to see if they have any suggestions. It would also be good to search the issue tracker for Code to see if there are other reports of behavior like this.

**Comment by timosperisen** [comment]
No problem.

I quickly searched the vscode repo and found this fresh one [#85278](https://github.com/microsoft/vscode/issues/85278) that sounds similar but unfortunately has not too much information.

Perhaps this is somehow related to the behavior I am experiencing.

**Comment by DavidAnson** [comment]
Please have a look at https://github.com/microsoft/vscode/issues/85089 and especially the thread at https://github.com/microsoft/vscode/issues/84803 to see if that helps?

**Comment by timosperisen** [comment]
I tested vscode insider release on one machine. The problem does not happen there.

```
Version: 1.41.0-insider (system setup)
Commit: f24f483428f592a262dc73d68a3f05745c562b31
Date: 2019-11-21T10:43:20.960Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

On my working machine I use september release until the next official release. There the problem also does not occur.

```
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```


I guess it's the same nodejs locale issue the people in the issues you mentioned seem to have.
I'm closing this as this is solved by a future vscode release.

Thanks!
