### ISSUE TITLE
Settings are not applied

### ISSUE THREAD

**Issue by Stanzilla** [DavidAnson/vscode-markdownlint#96]
Example: 
![image](https://user-images.githubusercontent.com/75278/70598295-cafb8580-1bea-11ea-896c-d9a6102dc8d8.png)

I don't quite understand it since it's fine in the CLI

![image](https://user-images.githubusercontent.com/75278/70598324-db136500-1bea-11ea-85b6-1a3288595e0a.png)

**Comment by DavidAnson** [comment]
That file name is not supported by the VS Code extension. You probably want to rename it to .markdownlint.json which is supported by both. Complete details here: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

**Comment by Stanzilla** [comment]
Oh, that really is not clear from the instructions/wiki
