### ISSUE TITLE
Other file extensions like .mdx?

### ISSUE THREAD

**Issue by bravo-kernel** [DavidAnson/vscode-markdownlint#98]
Awesome extension, is it possible to check our `.mdx` files as well? I could not find any reference in the settings or the issues here so apologies if I am missing something obvious.

**Comment by DavidAnson** [comment]
Thank you! The extension is configured to work on all files that VS Code recognizes as being Markdown. Here’s the relevant part of the code: https://github.com/DavidAnson/vscode-markdownlint/blob/58eea72a2188a6ef9ecbe499fe1af90bbbeb3163/extension.js#L26-L38

If you configure Code to treat those files as Markdown, this should automatically work for you. This may help:
- https://code.visualstudio.com/docs/languages/identifiers
- https://medium.com/@John_Papa/associate-file-types-in-vs-code-14b19dbbacd0

**Comment by bravo-kernel** [comment]
Thank you for the quick response. I was 99% sure that I was being silly again, now I know for sure 💃 .

Awesome work man ❤️

**Comment by dprothero** [comment]
@DavidAnson the issue with the recommended solution is that we then lose the syntax highlighting that are unique to the "Markdown React" (`mdx`) language mode. It would be nice the extension could support other language modes so we get the best of both worlds.

**Comment by DavidAnson** [comment]
@dprothero, that does not seem to be a supported language identifier?

https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers

**Comment by dprothero** [comment]
Good point @DavidAnson. It gets added by an extension:
https://marketplace.visualstudio.com/items?itemName=JounQin.vscode-mdx

**Comment by DavidAnson** [comment]
I am not very familiar with MDX, but looking briefly at its syntax, my impression is that applying typical Markdown rules might generate a lot of violations for content that is otherwise perfectly acceptable (for example, embedded HTML). Maybe you have experience and can tell me otherwise? I could add the new language tag pretty easily, I think, but would not want to do so if the default experience is crummy.
